FROM electronuserland/builder:12

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends \
    p7zip-full \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . .

ENTRYPOINT ["./scripts/init.sh"]
CMD ["-p", "mac", "-u"]
