FROM electronuserland/builder

ENV NODE_VERSION 14.16.0

COPY ./scripts/install-nodejs.sh ./scripts/install-nodejs.sh

RUN ./scripts/install-nodejs.sh $NODE_VERSION \
  && apt-get update -y \
  && apt-get install -y --no-install-recommends \
    p7zip-full \
    bc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . .

ENTRYPOINT ["./scripts/init.sh"]
CMD ["-p", "mac", "-u"]
