FROM electronuserland/builder:14

ARG NODE_VERSION="14.16.0"

COPY ./scripts/helpers/install-nodejs.sh ./scripts/helpers/install-nodejs.sh

RUN ./scripts/helpers/install-nodejs.sh ${NODE_VERSION} \
  && apt-get update -y \
  && apt-get install -y --no-install-recommends \
    p7zip-full \
    bc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . .

ENTRYPOINT ["./scripts/init.sh"]
CMD ["-p", "mac", "-u"]
