FROM electronuserland/builder

ENV NODE_VERSION 12.18.3

COPY ./scripts/install-nodejs.sh ./scripts/install-nodejs.sh

RUN ./scripts/install-nodejs.sh $NODE_VERSION

COPY . .

ENTRYPOINT ["./scripts/build-ui.sh"]
CMD ["-i"]
