FROM electronuserland/builder:wine-05.18

RUN apt-get update && apt-get install -y --no-install-recommends \
    p7zip-full \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . .

ENTRYPOINT ["./scripts/init.sh"]
CMD ["-p", "win", "-u"]
