FROM electronuserland/builder:18

ARG NODE_VERSION="18.17.1"

ENV IS_BFX_API_STAGING=${IS_BFX_API_STAGING:-0}
ENV IS_DEV_ENV=${IS_DEV_ENV:-0}

COPY ./scripts/helpers/install-nodejs.sh ./scripts/helpers/install-nodejs.sh

RUN ./scripts/helpers/install-nodejs.sh ${NODE_VERSION}

COPY . .

ENTRYPOINT ["./scripts/build-ui.sh"]
