FROM electronuserland/builder:10

RUN apt-get install -y --no-install-recommends \
    p7zip-full \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . .

ENTRYPOINT ["./scripts/init.sh"]
CMD ["-p", "linux", "-u"]
