'use strict'

const moment = require('moment')
const { randomInt } = require('node:crypto')

const userAccountStart = Date.UTC(2013, 0, 1)
const numberOfEntriesPerDay = 1_000
const msPerDay = 24 * 60 * 60 * 1_000
const msBetweenEnrties = msPerDay / (numberOfEntriesPerDay - 1)

const getMtsArray = (params) => {
  const start = Math.max(userAccountStart, params?.start ?? 0)
  const end = Math.min(Date.now(), params?.end ?? Date.now())
  const limit = Math.min(10_000, params?.limit ?? 10_000)
  const order = params?.order ?? -1
  const isASC = order > 0

  const res = []

  const timePoint = isASC ? start : end
  const roundOff = (ms) => (
    isASC ? Math.ceil(ms) : Math.floor(ms)
  )
  const mDate = moment.utc(timePoint)
  const year = mDate.year()
  const month = mDate.month()
  const date = mDate.date()
  const mDateOfDay = moment.utc({ year, month, date })
  const mDateOfDayMs = mDateOfDay.valueOf()
  const diff = mDate.diff(mDateOfDay)
  const firstPointMs = diff === 0
    ? timePoint
    : mDateOfDayMs + (
      roundOff(diff / msBetweenEnrties) * msBetweenEnrties
    )

  for (let i = 0; res.length < limit; i += 1) {
    const ms = isASC
      ? firstPointMs + (msBetweenEnrties * i)
      : firstPointMs - (msBetweenEnrties * i)

    if (isASC && ms > end) {
      break
    }
    if (!isASC && ms < start) {
      break
    }

    res.push(Math.trunc(ms))
  }

  return res
}

const getIdByMts = (mts = Date.now()) => (
  Number.parseInt(`${mts}${randomInt(100, 1000)}`)
)

const getOneFromRangeByCounter = (counter = 0, range = []) => {
  const i = counter % range.length

  return range[i]
}

const ccyList = ['BTC', 'ETH', 'LTC', 'UST', 'USD']
const ledgerDescriptionList = [
  'Crypto Withdrawal fee on wallet exchange',
  'Transfer of 1020.0 UST from wallet Exchange to Exchange SA(ezewer->ezewert) on wallet exchange',
  'Exchange 0.136 AAVE for USD @ 60.343 on wallet exchange',
  'Trading fees for 0.005778 XAUT (XAUT:USD) @ 1896.6 on BFX (0.2%) on wallet exchange',
  'Margin Funding Charge on wallet margin',
  'Settlement @ 1.0005 on wallet margin',
  'Position closed @ 1.0001 (TRADE) on wallet margin',
  'Position #168174072 funding cost on wallet margin'
]

module.exports = new Map([
  [
    'platform_status',
    () => [1]
  ],
  [
    'login',
    () => [
      '12345678-8888-4321-1234-8cb090a01360',
      [
        [
          'otp',
          true
        ]
      ]
    ]
  ],
  [
    'login_verify',
    () => [
      'pub:api:88888888-4444-4444-4444-121212121212-caps:s:o:f:w:wd:a-write',
      '2023-03-21T12:00:00.000Z'
    ]
  ],
  [
    'generate_token',
    () => ['pub:api:88888888-4444-4444-4444-121212121212-caps:s:o:f:w:wd:a-write']
  ],
  [
    'delete_token',
    () => [1]
  ],
  [
    'user_info',
    () => [
      123,
      'fake@email.fake',
      'fakename',
      null,
      null,
      null,
      null,
      'Timisoara'
    ]
  ],
  [
    'ledgers',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const num = 0.001 * (i + 1)

          return [
            getIdByMts(mts),
            getOneFromRangeByCounter(i, ccyList),
            null,
            mts,
            null,
            num * (i % 2 ? -1 : 1),
            num,
            null,
            getOneFromRangeByCounter(i, ledgerDescriptionList)
          ]
        })
    }
  ],
  [
    'symbols',
    [[
      '1INCH:USD',
      '1INCH:UST',
      'AAVE:USD',
      'AAVE:UST',
      'ADABTC',
      'ADAUSD',
      'ADAUST',
      'AIOZ:USD',
      'ALGUSD',
      'ALT11M2507:USD',
      'ALT11M2507:UST',
      'ALT11M250830:USD',
      'ALT11M250830:UST',
      'ALT11M251029:USD',
      'ALT11M251029:UST',
      'ALT2612:USD',
      'ALT2612:UST',
      'AMPUSD',
      'AMPUST',
      'APENFT:USD',
      'APEUSD',
      'APEUST',
      'APTUSD',
      'APTUST',
      'ARBUSD',
      'ARBUST',
      'ATHUSD',
      'ATHUST',
      'ATOUSD',
      'ATOUST',
      'AUSDT:USD',
      'AUSDT:UST',
      'AVAX:BTC',
      'AVAX:USD',
      'AVAX:UST',
      'AZERO:USD',
      'AZERO:UST',
      'B2MUSD',
      'B2MUST',
      'BCHN:USD',
      'BEST:USD',
      'BGBUSD',
      'BGBUST',
      'BLAST:USD',
      'BLAST:UST',
      'BONK:USD',
      'BONK:UST',
      'BTC:USDR',
      'BTC:XAUT',
      'BTCEUR',
      'BTCGBP',
      'BTCJPY',
      'BTCTRY',
      'BTCUSD',
      'BTCUST',
      'BTTUSD',
      'BXNUSD',
      'BXNUST',
      'CCDUSD',
      'CCDUST',
      'CELO:USD',
      'CELO:UST',
      'CHEX:USD',
      'CHZUSD',
      'CHZUST',
      'CNHT:USD',
      'COMP:USD',
      'COMP:UST',
      'CRVUSD',
      'CRVUST',
      'DAIUSD',
      'DOGE:BTC',
      'DOGE:USD',
      'DOGE:UST',
      'DOPUSD',
      'DOPUST',
      'DOTUSD',
      'DOTUST',
      'DSHBTC',
      'DSHUSD',
      'DYMUSD',
      'DYMUST',
      'EGLD:USD',
      'EGLD:UST',
      'EIGEN:USD',
      'EIGEN:UST',
      'ENAUSD',
      'ENAUST',
      'EOSBTC',
      'EOSUSD',
      'EOSUST',
      'ETCBTC',
      'ETCUSD',
      'ETCUST',
      'ETH2X:ETH',
      'ETH2X:USD',
      'ETH2X:UST',
      'ETH:XAUT',
      'ETHBTC',
      'ETHEUR',
      'ETHGBP',
      'ETHJPY',
      'ETHUSD',
      'ETHUST',
      'ETHW:USD',
      'ETHW:UST',
      'EURQ:USD',
      'EURQ:UST',
      'EURR:USD',
      'EURR:UST',
      'EURUST',
      'EUTUSD',
      'EUTUST',
      'FETUSD',
      'FETUST',
      'FILUSD',
      'FILUST',
      'FLOKI:USD',
      'FLOKI:UST',
      'FTMUSD',
      'FTMUST',
      'GALA:USD',
      'GALA:UST',
      'GBPUST',
      'GMMT:USD',
      'GMMT:UST',
      'GOMINING:USD',
      'GOMINING:UST',
      'GRTUSD',
      'GRTUST',
      'GTXUSD',
      'GTXUST',
      'HILSV:USD',
      'HIXUSD',
      'HIXUST',
      'HMSTR:USD',
      'HMSTR:UST',
      'HTXDAO:USD',
      'HTXDAO:UST',
      'ICPUSD',
      'ICPUST',
      'IOTBTC',
      'IOTUSD',
      'JASMY:USD',
      'JASMY:UST',
      'JPYUST',
      'JSTUSD',
      'JSTUST',
      'JUPUSD',
      'JUPUST',
      'JUSTICE:USD',
      'JUSTICE:UST',
      'JXXUSD',
      'JXXUST',
      'KANUSD',
      'KANUST',
      'KARATE:USD',
      'KARATE:UST',
      'KAVA:USD',
      'KAVA:UST',
      'KMNO:USD',
      'KMNO:UST',
      'LDOUSD',
      'LDOUST',
      'LEOBTC',
      'LEOETH',
      'LEOUSD',
      'LEOUST',
      'LIFIII:USD',
      'LIFIII:UST',
      'LINK:USD',
      'LINK:UST',
      'LTCBTC',
      'LTCUSD',
      'LTCUST',
      'MANEKI:USD',
      'MANEKI:UST',
      'MATIC:BTC',
      'MATIC:USD',
      'MATIC:UST',
      'MEWUSD',
      'MEWUST',
      'MIMUSD',
      'MIMUST',
      'MKRUSD',
      'MKRUST',
      'MLNUSD',
      'MNAUSD',
      'MPCUSD',
      'MPCUST',
      'MXNT:USD',
      'NEAR:USD',
      'NEAR:UST',
      'NEOUSD',
      'NEOUST',
      'NEXO:BTC',
      'NEXO:USD',
      'NEXO:UST',
      'NOTUSD',
      'NOTUST',
      'NYMUSD',
      'NYMUST',
      'OMGBTC',
      'OMGUSD',
      'OMNUSD',
      'OPXUSD',
      'OPXUST',
      'PEPE:USD',
      'PEPE:UST',
      'PNKUSD',
      'POLUSD',
      'POLUST',
      'RRTUSD',
      'SAND:USD',
      'SAND:UST',
      'SCROLL:USD',
      'SCROLL:UST',
      'SEIUSD',
      'SEIUST',
      'SHIB:USD',
      'SHIB:UST',
      'SOLBTC',
      'SOLUSD',
      'SOLUST',
      'SPEC:USD',
      'SPEC:UST',
      'SPELL:USD',
      'SPELL:UST',
      'STGUSD',
      'STGUST',
      'STRK:USD',
      'STRK:UST',
      'SUIUSD',
      'SUIUST',
      'SUNUSD',
      'SUNUST',
      'SUSHI:USD',
      'SUSHI:UST',
      'SWEAT:USD',
      'SWEAT:UST',
      'TESTADA:TESTUSD',
      'TESTALGO:TESTUSD',
      'TESTAPT:TESTUSD',
      'TESTAVAX:TESTUSD',
      'TESTBTC:TESTUSD',
      'TESTBTC:TESTUSDT',
      'TESTDOGE:TESTUSD',
      'TESTDOT:TESTUSD',
      'TESTEOS:TESTUSD',
      'TESTETH:TESTUSD',
      'TESTFIL:TESTUSD',
      'TESTLTC:TESTUSD',
      'TESTMATIC:TESTUSD',
      'TESTMATIC:TESTUSDT',
      'TESTNEAR:TESTUSD',
      'TESTSOL:TESTUSD',
      'TESTXAUT:TESTUSD',
      'TESTXTZ:TESTUSD',
      'TIAUSD',
      'TIAUST',
      'TITAN1:GBP',
      'TITAN1:USD',
      'TITAN2:GBP',
      'TITAN2:USD',
      'TOKEN:USD',
      'TOKEN:UST',
      'TOMI:USD',
      'TOMI:UST',
      'TONUSD',
      'TONUST',
      'TRXBTC',
      'TRXEUR',
      'TRXUSD',
      'TRXUST',
      'TRYUST',
      'TSDUSD',
      'TSDUST',
      'TURBO:USD',
      'TURBO:UST',
      'UDCUSD',
      'UDCUST',
      'UNIUSD',
      'UNIUST',
      'UOSBTC',
      'UOSUSD',
      'USDQ:USD',
      'USDQ:UST',
      'USDR:USD',
      'USDR:UST',
      'UST:CNHT',
      'UST:MXNT',
      'USTBL:USD',
      'USTBL:UST',
      'USTUSD',
      'UXLINK:USD',
      'UXLINK:UST',
      'VELAR:USD',
      'VELAR:UST',
      'WBTBTC',
      'WBTUSD',
      'WHBT:USD',
      'WHBT:UST',
      'WIFUSD',
      'WIFUST',
      'WILD:USD',
      'WOOUSD',
      'WOOUST',
      'XAUT:BTC',
      'XAUT:USD',
      'XAUT:UST',
      'XDCUSD',
      'XDCUST',
      'XLMBTC',
      'XLMUSD',
      'XLMUST',
      'XMRBTC',
      'XMRUSD',
      'XMRUST',
      'XRDBTC',
      'XRDUSD',
      'XRPBTC',
      'XRPUSD',
      'XRPUST',
      'XTPUSD',
      'XTPUST',
      'XTZUSD',
      'YFIUSD',
      'YFIUST',
      'ZECBTC',
      'ZECUSD',
      'ZKXUSD',
      'ZKXUST',
      'ZROUSD',
      'ZROUST',
      'ZRXUSD'
    ]]
  ],
  [
    'map_symbols',
    [[
      [
        'BTCF0:USTF0',
        'BTC-PERP'
      ],
      [
        'ETHF0:USTF0',
        'ETH-PERP'
      ],
      [
        'AMPF0:USTF0',
        'AMPL-PERP'
      ],
      [
        'XAUTF0:USTF0',
        'XAUT-PERP'
      ],
      [
        'XAGF0:USTF0',
        'XAG-PERP'
      ],
      [
        'EUROPE50IXF0:USTF0',
        'EUROPE50'
      ],
      [
        'GERMANY30IXF0:USTF0',
        'GERMANY30-PERP'
      ],
      [
        'LINKF0:USTF0',
        'LINK-PERP'
      ],
      [
        'DOTF0:USTF0',
        'DOT-PERP'
      ],
      [
        'UNIF0:USTF0',
        'UNI-PERP'
      ],
      [
        'LTCF0:USTF0',
        'LTC-PERP'
      ],
      [
        'IOTF0:USTF0',
        'IOT-PERP'
      ],
      [
        'EOSF0:USTF0',
        'EOS-PERP'
      ],
      [
        'BTCDOMF0:USTF0',
        'BTCDOM-PERP'
      ],
      [
        'EURF0:USTF0',
        'EUR-PERP'
      ],
      [
        'JPYF0:USTF0',
        'JPY-PERP'
      ],
      [
        'GBPF0:USTF0',
        'GBP-PERP'
      ],
      [
        'ETHF0:BTCF0',
        'ETH/BTC-PERP'
      ],
      [
        'ADAF0:USTF0',
        'ADA-PERP'
      ],
      [
        'XLMF0:USTF0',
        'XLM-PERP'
      ],
      [
        'LTCF0:BTCF0',
        'LTC/BTC-PERP'
      ],
      [
        'DOTF0:BTCF0',
        'DOT/BTC-PERP'
      ],
      [
        'XAUTF0:BTCF0',
        'XAUT/BTC-PERP'
      ],
      [
        'DOGEF0:USTF0',
        'DOGE-PERP'
      ],
      [
        'SOLF0:USTF0',
        'SOL-PERP'
      ],
      [
        'SUSHIF0:USTF0',
        'SUSHI-PERP'
      ],
      [
        'AVAXF0:USTF0',
        'AVAX-PERP'
      ],
      [
        'FILF0:USTF0',
        'FIL-PERP'
      ],
      [
        'XMRF0:USTF0',
        'XMR-PERP'
      ],
      [
        'XRPF0:USTF0',
        'XRP-PERP'
      ],
      [
        'XRPF0:BTCF0',
        'XRP/BTC-PERP'
      ],
      [
        'ALGF0:USTF0',
        'ALGO-PERP'
      ],
      [
        'GERMANY40IXF0:USTF0',
        'GERMANY40'
      ],
      [
        'AAVEF0:USTF0',
        'AAVE-PERP'
      ],
      [
        'MATICF0:USTF0',
        'MATIC-PERP'
      ],
      [
        'FTMF0:USTF0',
        'FTM-PERP'
      ],
      [
        'EGLDF0:USTF0',
        'EGLD-PERP'
      ],
      [
        'AXSF0:USTF0',
        'AXS-PERP'
      ],
      [
        'COMPF0:USTF0',
        'COMP-PERP'
      ],
      [
        'XTZF0:USTF0',
        'XTZ-PERP'
      ],
      [
        'TRXF0:USTF0',
        'TRX-PERP'
      ],
      [
        'ATOF0:USTF0',
        'ATOM-PERP'
      ],
      [
        'SOLF0:BTCF0',
        'SOL/BTC-PERP'
      ],
      [
        'AVAXF0:BTCF0',
        'AVAX/BTC-PERP'
      ],
      [
        'SHIBF0:USTF0',
        'SHIB-PERP'
      ],
      [
        'OMGF0:USTF0',
        'OMG-PERP'
      ],
      [
        'BTCF0:EUTF0',
        'BTC/EURt-PERP'
      ],
      [
        'ETHF0:EUTF0',
        'ETH/EURt-PERP'
      ],
      [
        'ZECF0:USTF0',
        'ZEC-PERP'
      ],
      [
        'NEOF0:USTF0',
        'NEO-PERP'
      ],
      [
        'CRVF0:USTF0',
        'CRV-PERP'
      ],
      [
        'ICPF0:USTF0',
        'ICP-PERP'
      ],
      [
        'NEARF0:USTF0',
        'NEAR-PERP'
      ],
      [
        'APEF0:USTF0',
        'APE-PERP'
      ],
      [
        'GALAF0:USTF0',
        'GALA-PERP'
      ],
      [
        'ETCF0:USTF0',
        'ETC-PERP'
      ],
      [
        'ANCF0:USTF0',
        'ANC-PERP'
      ],
      [
        'WAVESF0:USTF0',
        'WAVES-PERP'
      ],
      [
        'JASMYF0:USTF0',
        'JASMY-PERP'
      ],
      [
        'KNCF0:USTF0',
        'KNC-PERP'
      ],
      [
        'STGF0:USTF0',
        'STG-PERP'
      ],
      [
        'MKRF0:USTF0',
        'MKR-PERP'
      ],
      [
        'SANDF0:USTF0',
        'SAND-PERP'
      ],
      [
        'APTF0:USTF0',
        'APT-PERP'
      ],
      [
        'UKOILF0:USTF0',
        'UKOIL-PERP'
      ],
      [
        'XPDF0:USTF0',
        'XPD-PERP'
      ],
      [
        'XPTF0:USTF0',
        'XPT-PERP'
      ],
      [
        'ARBF0:USTF0',
        'ARB-PERP'
      ],
      [
        'FRANCE40IXF0:USTF0',
        'FRANCE40'
      ],
      [
        'SPAIN35IXF0:USTF0',
        'SPAIN35'
      ],
      [
        'UK100IXF0:USTF0',
        'UK100'
      ],
      [
        'TESTBTCF0:TESTUSDTF0',
        'BTC-PERP'
      ],
      [
        'TESTMATICF0:TESTUSDTF0',
        'MATIC-PERP'
      ],
      [
        'TESTDOTF0:TESTUSDTF0',
        'DOT-PERP'
      ],
      [
        'TESTSOLF0:TESTUSDTF0',
        'SOL-PERP'
      ],
      [
        'JAPAN225IXF0:USTF0',
        'JAPAN225'
      ],
      [
        'HONGKONG50IXF0:USTF0',
        'HONGKONG50'
      ],
      [
        'AUSTRALIA200IXF0:USTF0',
        'AUSTRALIA200'
      ],
      [
        'TESTXAUTF0:TESTUSDTF0',
        'XAUT-PERP'
      ],
      [
        'TESTETHF0:TESTUSDTF0',
        'ETH-PERP'
      ],
      [
        'TESTAVAXF0:TESTUSDTF0',
        'AVAX-PERP'
      ],
      [
        'TESTDOGEF0:TESTUSDTF0',
        'DOGE-PERP'
      ],
      [
        'TESTXTZF0:TESTUSDTF0',
        'XTZ-PERP'
      ],
      [
        'TESTALGOF0:TESTUSDTF0',
        'ALGO-PERP'
      ],
      [
        'TESTNEARF0:TESTUSDTF0',
        'NEAR-PERP'
      ],
      [
        'TESTFILF0:TESTUSDTF0',
        'FIL-PERP'
      ],
      [
        'TESTADAF0:TESTUSDTF0',
        'ADA-PERP'
      ],
      [
        'TESTLTCF0:TESTUSDTF0',
        'LTC-PERP'
      ],
      [
        'TESTAPTF0:TESTUSDTF0',
        'APT-PERP'
      ],
      [
        'TESTEOSF0:TESTUSDTF0',
        'EOS-PERP'
      ],
      [
        'TRYF0:USTF0',
        'TRY-PERP'
      ],
      [
        'BNBF0:USTF0',
        'BNB-PERP'
      ],
      [
        'WLDF0:USTF0',
        'WLD-PERP'
      ],
      [
        'BVIVF0:USTF0',
        'BVIV-PERP'
      ],
      [
        'EVIVF0:USTF0',
        'EVIV-PERP'
      ],
      [
        'CHZF0:USTF0',
        'CHZ-PERP'
      ],
      [
        'POLF0:USTF0',
        'POL-PERP'
      ],
      [
        'PEPEF0:USTF0',
        'PEPE-PERP'
      ],
      [
        'SUIF0:USTF0',
        'SUI-PERP'
      ],
      [
        'TONF0:USTF0',
        'TON-PERP'
      ]
    ]]
  ],
  [
    'inactive_currencies',
    [[
      'AAA',
      'ABS',
      'ADD',
      'AGI',
      'AID',
      'AIO',
      'AIX',
      'ALBT',
      'AMPF0',
      'ANC',
      'ANCF0',
      'ANT',
      'APP',
      'AST',
      'ATD',
      'ATLAS',
      'ATM',
      'AUC',
      'AVT',
      'B21X',
      'BAB',
      'BAND',
      'BAT',
      'BBB',
      'BBN',
      'BCC',
      'BCHABC',
      'BCI',
      'BCU',
      'BFT',
      'BMI',
      'BNT',
      'BOBA',
      'BOO',
      'BOX',
      'BRISE',
      'BSV',
      'BT1',
      'BT2',
      'BTG',
      'BTSE',
      'CBT',
      'CEL',
      'CFI',
      'CHSB',
      'CLO',
      'CND',
      'CNN',
      'CONV',
      'CSTBCHABC',
      'CSTBCHN',
      'CSX',
      'CTK',
      'CTX',
      'DAD',
      'DAPP',
      'DAT',
      'DCR',
      'DGB',
      'DGX',
      'DOG',
      'DORA',
      'DRN',
      'DTA',
      'DTH',
      'DTX',
      'DUSK',
      'DVF',
      'EDO',
      'ELF',
      'ENJ',
      'EOSDT',
      'EOX',
      'ESS',
      'ETP',
      'EUS',
      'EVT',
      'EXO',
      'FBT',
      'FCL',
      'FOA',
      'FSN',
      'FTMF0',
      'FTT',
      'FUN',
      'GEN',
      'GERMANY30IXF0',
      'GMT',
      'GNT',
      'GOC',
      'GOT',
      'GPT',
      'GSD',
      'GST',
      'GXT',
      'HEC',
      'HEZ',
      'HMT',
      'HMTPLG',
      'HOT',
      'HTX',
      'ICE',
      'IDX',
      'IMP',
      'INT',
      'IOS',
      'IQX',
      'KAI',
      'KNC',
      'KNCF0',
      'KSM',
      'LAI',
      'LOO',
      'LRC',
      'LUNA',
      'LUXO',
      'MAN',
      'MATICF0',
      'MATICM',
      'MEME',
      'MGO',
      'MIR',
      'MIT',
      'MOB',
      'MSC',
      'MTN',
      'MTO',
      'NCA',
      'NEC',
      'NIO',
      'NOM',
      'NUT',
      'NXRA',
      'OCEAN',
      'ODE',
      'OGN',
      'OKB',
      'ONE',
      'ONL',
      'ONUS',
      'ORS',
      'OXY',
      'PAI',
      'PANTEOS',
      'PAS',
      'PBALEOS',
      'PBANDEOS',
      'PBATEOS',
      'PBTCEOS',
      'PBTCETH',
      'PCOMPEOS',
      'PDAIEOS',
      'PEOSETH',
      'PETHEOS',
      'PLANETS',
      'PLINKEOS',
      'PLRCEOS',
      'PLTCEOS',
      'PLTCETH',
      'PMKREOS',
      'PNG',
      'POA',
      'POLC',
      'POLIS',
      'POMGEOS',
      'POY',
      'PPNKEOS',
      'PPNTEOS',
      'PREPEOS',
      'PRMX',
      'PSNXEOS',
      'PUNIEOS',
      'PUOSEOS',
      'PYFIEOS',
      'PZRXEOS',
      'QRDO',
      'QSH',
      'QTF',
      'RBT',
      'RCN',
      'RDN',
      'REEF',
      'REP',
      'REQ',
      'RIF',
      'RINGX',
      'RLC',
      'ROSE',
      'RRB',
      'RTE',
      'SAN',
      'SCR',
      'SEE',
      'SEN',
      'SENATE',
      'SGB',
      'SHFT',
      'SHFTM',
      'SIDUS',
      'SMR',
      'SNG',
      'SNT',
      'SPK',
      'SRM',
      'STJ',
      'SWM',
      'SXX',
      'TENET',
      'TERRAUST',
      'TESTMATICF0',
      'TH1',
      'THETA',
      'TKN',
      'TNB',
      'TREEB',
      'TRI',
      'TST',
      'UFR',
      'UOP',
      'USDTDVF',
      'USDTHEZ',
      'USDTOMG',
      'USK',
      'UTK',
      'UTN',
      'VEE',
      'VELO',
      'VEN',
      'VLD',
      'VRA',
      'VSY',
      'WAX',
      'WLO',
      'WMINIMA',
      'WPR',
      'WTC',
      'XCAD',
      'XCH',
      'XCN',
      'XRA',
      'XSN',
      'YGG',
      'YYW',
      'ZBT',
      'ZCN',
      'ZIL',
      'ZMT'
    ]]
  ],
  [
    'margin_currencies',
    [[
      'ADA',
      'ALG',
      'AMP',
      'APE',
      'APT',
      'ATO',
      'AVAX',
      'BCHN',
      'BTC',
      'COMP',
      'DAI',
      'DOGE',
      'DOT',
      'DSH',
      'EGLD',
      'EOS',
      'ETC',
      'ETH',
      'ETHW',
      'EUR',
      'FIL',
      'FTM',
      'GBP',
      'IOT',
      'JPY',
      'LEO',
      'LINK',
      'LTC',
      'MATIC',
      'MKR',
      'MXNT',
      'NEO',
      'SHIB',
      'SOL',
      'SUSHI',
      'TESTADA',
      'TESTALGO',
      'TESTAPT',
      'TESTAVAX',
      'TESTBTC',
      'TESTDOGE',
      'TESTDOT',
      'TESTEOS',
      'TESTETH',
      'TESTFIL',
      'TESTLTC',
      'TESTMATIC',
      'TESTNEAR',
      'TESTSOL',
      'TESTUSD',
      'TESTUSDT',
      'TESTXAUT',
      'TESTXTZ',
      'TRX',
      'TRY',
      'UNI',
      'USD',
      'UST',
      'XAUT',
      'XLM',
      'XMR',
      'XRP',
      'ZEC',
      'ZRX'
    ]]
  ]
])
