'use strict'

const moment = require('moment')
const { randomInt } = require('node:crypto')

const userAccountStart = Date.UTC(2013, 0, 1)
const numberOfEntriesPerDay = 1_000
const msPerDay = 24 * 60 * 60 * 1_000
const msBetweenEnrties = msPerDay / (numberOfEntriesPerDay - 1)

const getMtsArray = (params, opts) => {
  const start = Math.max(userAccountStart, params?.start ?? 0)
  const end = Math.min(Date.now(), params?.end ?? Date.now())
  const limit = Math.min(10_000, params?.limit ?? 10_000)
  const order = params?.order ?? -1
  const isASC = order > 0
  const _msBetweenEnrties = opts?.msBetweenEnrties ?? msBetweenEnrties

  const res = []

  if (end <= userAccountStart) {
    return res
  }

  const timePoint = isASC ? start : end
  const roundOff = (ms) => (
    isASC ? Math.ceil(ms) : Math.floor(ms)
  )
  const mDateOfTimePoint = moment.utc(timePoint)
  const transTimePoint = isASC
    ? timePoint + _msBetweenEnrties
    : timePoint - _msBetweenEnrties
  const mDate = mDateOfTimePoint.isSame(transTimePoint, 'day')
    ? mDateOfTimePoint
    : moment.utc(transTimePoint)
  const year = mDate.year()
  const month = mDate.month()
  const date = mDate.date()
  const mDateOfDay = moment.utc({ year, month, date })
  const mDateOfDayMs = mDateOfDay.valueOf()
  const diff = mDate.diff(mDateOfDay)
  const firstPointMs = diff === 0
    ? timePoint
    : mDateOfDayMs + (
      roundOff(diff / _msBetweenEnrties) * _msBetweenEnrties
    )

  for (let i = 0; res.length < limit; i += 1) {
    const ms = isASC
      ? firstPointMs + (_msBetweenEnrties * i)
      : firstPointMs - (_msBetweenEnrties * i)

    if (isASC && ms > end) {
      break
    }
    if (!isASC && ms < start) {
      break
    }

    res.push(Math.trunc(ms))
  }

  return res
}

const getIdByMts = (mts = Date.now()) => (
  Number.parseInt(`${mts}${randomInt(100, 1000)}`)
)

const getOneFromRangeByCounter = (counter = 0, range = []) => {
  const i = counter % range.length

  return range[i]
}

const getPairFromCcyRangeByCounter = (
  counter = 0,
  range = [],
  opts
) => {
  const {
    prefix = 't',
    suffix = ''
  } = opts ?? {}
  const i = counter % range.length
  const j = (counter + 1) % range.length
  const first = `${range[i]}${suffix}`
  const second = `${range[j]}${suffix}`
  const separator = (
    first.length > 3 ||
    second.length > 3
  )
    ? ':'
    : ''

  return `${prefix}${first}${separator}${second}`
}

const ccyList = ['BTC', 'ETH', 'LTC', 'UST', 'USD']
const ledgerDescriptionList = [
  'Crypto Withdrawal fee on wallet exchange',
  'Transfer of 1020.0 UST from wallet Exchange to Exchange SA(ezewer->ezewert) on wallet exchange',
  'Exchange 0.136 AAVE for USD @ 60.343 on wallet exchange',
  'Trading fees for 0.005778 XAUT (XAUT:USD) @ 1896.6 on BFX (0.2%) on wallet exchange',
  'Margin Funding Charge on wallet margin',
  'Settlement @ 1.0005 on wallet margin',
  'Position closed @ 1.0001 (TRADE) on wallet margin',
  'Position #168174072 funding cost on wallet margin'
]
const orderTypeList = [
  'EXCHANGE MARKET',
  'EXCHANGE LIMIT',
  'MARKET',
  'LIMIT'
]
const orderStatusList = [
  'CANCELED',
  'EXECUTED',
  'POSTONLY CANCELED'
]

module.exports = new Map([
  [
    'ledgers',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const balance = mts / 100_000_000_000

          return [
            getIdByMts(mts),
            args?.symbol ?? getOneFromRangeByCounter(mts, ccyList),
            null,
            mts,
            null,
            balance * (i % 2 ? -0.1 : 0.1),
            balance,
            null,
            getOneFromRangeByCounter(mts, ledgerDescriptionList)
          ]
        })
    }
  ],
  [
    'trades',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            id,
            args?.symbol ?? getPairFromCcyRangeByCounter(mts, ccyList),
            mts,
            id,
            price * (i % 2 ? -0.1 : 0.1),
            price,
            getOneFromRangeByCounter(mts, orderTypeList),
            price,
            i % 2,
            price * -0.01,
            getOneFromRangeByCounter(mts, ccyList),
            id
          ]
        })
    }
  ],
  [
    'f_trade_hist',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const amount = mts / 100_000_000_000

          return [
            id,
            args?.symbol ?? `f${getOneFromRangeByCounter(mts, ccyList)}`,
            mts,
            id,
            amount * (i % 2 ? -0.1 : 0.1),
            amount * 0.001,
            i % 120,
            null
          ]
        })
    }
  ],
  [
    'public_trades',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            id,
            mts,
            price * 0.1,
            price
          ]
        })
    }
  ],
  [
    'status_messages',
    (args) => {
      return getMtsArray(
        { end: Date.UTC(2025, 0, 1), limit: 100 },
        { msBetweenEnrties: msPerDay }
      )
        .map((mts, i) => {
          const price = mts / 100_000_000_000
          const key = (args?.keys ?? ['ALL']).some((k) => k === 'ALL')
            ? getPairFromCcyRangeByCounter(mts, ccyList, { suffix: 'F0' })
            : getOneFromRangeByCounter(mts, args?.keys)

          return [
            key,
            mts,
            null,
            price,
            price,
            null,
            price * 100,
            null,
            mts,
            price * 0.1,
            6,
            null,
            price * -0.01,
            null,
            null,
            price,
            null,
            null,
            price * 100,
            null,
            null,
            null,
            0.0005,
            0.0025
          ]
        })
    }
  ],
  [
    'orders',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            id,
            100,
            mts,
            args?.symbol ?? getPairFromCcyRangeByCounter(mts, ccyList),
            mts,
            mts,
            price * 0.1,
            price * 0.1,
            getOneFromRangeByCounter(mts, orderTypeList),
            null,
            null,
            null,
            '0',
            getOneFromRangeByCounter(mts, orderStatusList),
            null,
            null,
            price,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            { _$F7: 1 }
          ]
        })
    }
  ],
  [
    'active_orders',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            id,
            null,
            mts,
            args?.symbol ?? getPairFromCcyRangeByCounter(mts, ccyList),
            mts,
            mts,
            price * 0.1,
            price * 0.1,
            getOneFromRangeByCounter(mts, orderTypeList),
            null,
            null,
            null,
            '0',
            'ACTIVE',
            null,
            null,
            price,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            { _$F7: 1 }
          ]
        })
    }
  ],
  [
    'order_trades',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            id,
            args?.symbol ?? getPairFromCcyRangeByCounter(mts, ccyList),
            mts,
            args?.orderId ?? id,
            price * 0.01,
            price,
            null,
            null,
            i % 2 ? -1 : 1,
            price * -0.001,
            getOneFromRangeByCounter(mts, ccyList),
            id
          ]
        })
    }
  ],
  [
    'movements',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const amount = mts / 100_000_000_000
          const ccy = args?.ccy ?? getPairFromCcyRangeByCounter(mts, ccyList)

          return [
            id,
            ccy,
            `${ccy}_MOCKED_CCY_NAME`,
            null,
            null,
            mts,
            mts,
            null,
            null,
            'COMPLETED',
            null,
            null,
            amount * (i % 2 ? -0.1 : 0.1),
            amount * -0.001,
            null,
            null,
            args?.address ?? id,
            null,
            null,
            null,
            id,
            null
          ]
        })
    }
  ],
  [
    'f_offer_hist',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const amount = mts / 10_000_000_000

          return [
            id,
            args?.symbol ?? `f${getOneFromRangeByCounter(mts, ccyList)}`,
            mts,
            mts,
            amount * (i % 2 ? -1 : 0),
            amount * -1,
            'LIMIT',
            null,
            null,
            null,
            i % 2 ? 'CANCELED' : 'EXECUTED',
            null,
            null,
            null,
            amount * 0.01,
            i % 120,
            0,
            0,
            null,
            null,
            null
          ]
        })
    }
  ],
  [
    'f_loan_hist',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const amount = mts / 10_000_000_000

          return [
            id,
            args?.symbol ?? `f${getOneFromRangeByCounter(mts, ccyList)}`,
            i % 2 ? -1 : 1,
            mts,
            mts,
            amount * (i % 2 ? -1 : 1),
            null,
            'CLOSED (used)',
            null,
            null,
            null,
            amount * 0.01,
            i % 120,
            mts,
            mts,
            null,
            0,
            null,
            0,
            null,
            0
          ]
        })
    }
  ],
  [
    'f_credit_hist',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const amount = mts / 10_000_000_000
          const symbol = args?.symbol ?? `f${getOneFromRangeByCounter(mts, ccyList)}`

          return [
            id,
            symbol,
            i % 2 ? -1 : 1,
            mts,
            mts,
            amount * (i % 2 ? -1 : 1),
            null,
            'CLOSED (expired)',
            'FIXED',
            null,
            null,
            amount * 0.01,
            i % 120,
            mts,
            mts,
            null,
            0,
            null,
            0,
            null,
            0,
            symbol.replace('f', '').length > 3
              ? `${symbol}:USD`
              : `${symbol}USD`
          ]
        })
    }
  ],
  [
    'positions_hist',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)

          return [
            args?.symbol ?? getPairFromCcyRangeByCounter(mts, ccyList),
            'CLOSED',
            0,
            mts / 100_000_000_000,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            id,
            mts,
            mts,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        })
    }
  ],
  [
    'positions_snap',
    (args) => {
      return getMtsArray(args)
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            args?.symbol ?? getPairFromCcyRangeByCounter(mts, ccyList),
            'ACTIVE',
            price * (i % 2 ? -0.01 : 0.01),
            price,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            id,
            mts,
            mts,
            null,
            null,
            null,
            null,
            null,
            null
          ]
        })
    }
  ],
  [
    'positions',
    (args) => {
      return getMtsArray(
        { end: Date.UTC(2025, 0, 1), limit: 100 },
        { msBetweenEnrties: msPerDay }
      )
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            getPairFromCcyRangeByCounter(mts, ccyList),
            'ACTIVE',
            price * (i % 2 ? -0.01 : 0.01),
            price,
            0,
            0,
            -0.33455568705000516,
            -0.0003117550117425625,
            price,
            3.0673001895895604,
            null,
            id,
            mts,
            mts,
            null,
            0,
            null,
            0,
            0,
            {
              reason: 'TRADE',
              order_id: id,
              liq_stage: null,
              trade_price: price,
              trade_amount: price * (i % 2 ? -0.01 : 0.01),
              order_id_oppo: id
            }
          ]
        })
    }
  ],
  [
    'positions_audit',
    (args) => {
      return getMtsArray(args, { msBetweenEnrties: msPerDay })
        .map((mts, i) => {
          const id = getIdByMts(mts)
          const price = mts / 100_000_000_000

          return [
            getPairFromCcyRangeByCounter(mts, ccyList),
            'ACTIVE',
            price * (i % 2 ? -0.01 : 0.01),
            price,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            getOneFromRangeByCounter(mts, args?.ids) ?? id,
            mts,
            mts,
            null,
            null,
            null,
            0,
            null,
            {
              reason: 'TRADE',
              order_id: id,
              liq_stage: null,
              trade_price: price,
              trade_amount: price * (i % 2 ? -0.01 : 0.01),
              order_id_oppo: id
            }
          ]
        })
    }
  ],
  [
    'logins_hist',
    (args) => {
      return getMtsArray(args)
        .map((mts) => {
          return [
            getIdByMts(mts),
            null,
            mts,
            null,
            '192.168.0.1',
            null,
            null,
            '{"asn": "28545, Cablemas Telecomunicaciones SA de CV", "geo": "Cancún, MX", "user_agent":   {"os": "Windows 10", "raw": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36", "browser": "Chrome", "version": "79.0.3945.117", "platform": "Windows", "is_mobile": false}}'
          ]
        })
    }
  ],
  [
    'change_log',
    (args) => {
      return getMtsArray(args)
        .map((mts) => {
          return [
            mts,
            null,
            'withdraw:request',
            null,
            null,
            '192.168.0.1',
            'Mozilla/5.0 (X11; CrOS x86_64 12499.51.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.92 Safari/537.36'
          ]
        })
    }
  ],
  [
    'invoice_list',
    (args) => {
      const mtsArr = args?.id
        ? [getMtsArray(args)[0]]
        : getMtsArray(args)

      return mtsArr
        .map((mts) => {
          const id = args?.id ?? getIdByMts(mts)
          const amount = mts / 10_000_000_000

          return {
            id,
            t: mts,
            type: 'ECOMMERCE',
            duration: 900,
            amount,
            currency: 'USD',
            orderId: `${id}`,
            payCurrencies: [
              'BTC',
              'ETH',
              'UST-ETH',
              'LNX'
            ],
            webhook: 'https://bfx-pay-123.321.com',
            redirectUrl: 'https://bfx-pay-123.321.com?page_id123',
            status: 'EXPIRED',
            customerInfo: {
              nationality: 'UA',
              residCountry: 'UA',
              residState: null,
              residCity: 'Kharkiv',
              residZipCode: '12345',
              residStreet: 'street',
              residBuildingNo: null,
              fullName: 'name user',
              email: 'user@mail.com',
              tosAccepted: true
            },
            invoices: [
              {
                amount,
                currency: 'BTC',
                payCurrency: 'BTC',
                poolCurrency: 'BTC',
                address: '1234567890qwerty'
              },
              {
                amount,
                currency: 'ETH',
                payCurrency: 'ETH',
                poolCurrency: 'ETH',
                address: '1234567890qwerty'
              },
              {
                amount,
                currency: 'UST',
                payCurrency: 'UST',
                poolCurrency: 'ETH',
                address: '1234567890qwerty'
              },
              {
                amount,
                currency: 'BTC',
                payCurrency: 'BTC',
                poolCurrency: 'LNX',
                address: '1234567890qwerty',
                ext: {
                  hash: '1234567890qwerty',
                  payment_request: '1234567890qwerty',
                  node_pub: '1234567890qwerty'
                }
              }
            ],
            payment: {
              txid: '1234567890qwerty',
              amount,
              currency: 'UST',
              method: 'TETHERUSE',
              status: 'COMPLETED',
              confirmations: 5,
              created_at: mts,
              updated_at: mts,
              depositId: id,
              ledgerId: id,
              forceCompleted: false,
              amountDiff: ''
            },
            additionalPayments: [
              {
                txid: '1234567890qwerty',
                amount,
                currency: 'UST',
                method: 'TETHERUSE',
                status: 'COMPLETED',
                confirmations: 5,
                created_at: mts,
                updated_at: mts,
                depositId: id,
                ledgerId: id
              }
            ],
            merchantName: 'Testing',
            meta: {},
            flags: ['COMPLETED'],
            recalculatedAt: mts
          }
        })
    }
  ],
  [
    'platform_status',
    () => [1]
  ],
  [
    'login',
    () => [
      '12345678-8888-4321-1234-8cb090a01360',
      [
        [
          'otp',
          true
        ]
      ]
    ]
  ],
  [
    'login_verify',
    () => [
      'pub:api:88888888-4444-4444-4444-121212121212-caps:s:o:f:w:wd:a-write',
      '2023-03-21T12:00:00.000Z'
    ]
  ],
  [
    'generate_token',
    () => ['pub:api:88888888-4444-4444-4444-121212121212-caps:s:o:f:w:wd:a-write']
  ],
  [
    'delete_token',
    () => [1]
  ],
  [
    'user_info',
    () => [
      123,
      'fake@email.fake',
      'fakename',
      null,
      null,
      null,
      null,
      'Timisoara'
    ]
  ],
  [
    'symbols',
    [[
      '1INCH:USD',
      '1INCH:UST',
      'AAVE:USD',
      'AAVE:UST',
      'ADABTC',
      'ADAUSD',
      'ADAUST',
      'AIOZ:USD',
      'ALGUSD',
      'ALT11M2507:USD',
      'ALT11M2507:UST',
      'ALT11M250830:USD',
      'ALT11M250830:UST',
      'ALT11M251029:USD',
      'ALT11M251029:UST',
      'ALT2612:USD',
      'ALT2612:UST',
      'AMPUSD',
      'AMPUST',
      'APENFT:USD',
      'APEUSD',
      'APEUST',
      'APTUSD',
      'APTUST',
      'ARBUSD',
      'ARBUST',
      'ATHUSD',
      'ATHUST',
      'ATOUSD',
      'ATOUST',
      'AUSDT:USD',
      'AUSDT:UST',
      'AVAX:BTC',
      'AVAX:USD',
      'AVAX:UST',
      'AZERO:USD',
      'AZERO:UST',
      'B2MUSD',
      'B2MUST',
      'BCHN:USD',
      'BEST:USD',
      'BGBUSD',
      'BGBUST',
      'BLAST:USD',
      'BLAST:UST',
      'BONK:USD',
      'BONK:UST',
      'BTC:USDR',
      'BTC:XAUT',
      'BTCEUR',
      'BTCGBP',
      'BTCJPY',
      'BTCTRY',
      'BTCUSD',
      'BTCUST',
      'BTTUSD',
      'BXNUSD',
      'BXNUST',
      'CCDUSD',
      'CCDUST',
      'CELO:USD',
      'CELO:UST',
      'CHEX:USD',
      'CHZUSD',
      'CHZUST',
      'CNHT:USD',
      'COMP:USD',
      'COMP:UST',
      'CRVUSD',
      'CRVUST',
      'DAIUSD',
      'DOGE:BTC',
      'DOGE:USD',
      'DOGE:UST',
      'DOPUSD',
      'DOPUST',
      'DOTUSD',
      'DOTUST',
      'DSHBTC',
      'DSHUSD',
      'DYMUSD',
      'DYMUST',
      'EGLD:USD',
      'EGLD:UST',
      'EIGEN:USD',
      'EIGEN:UST',
      'ENAUSD',
      'ENAUST',
      'EOSBTC',
      'EOSUSD',
      'EOSUST',
      'ETCBTC',
      'ETCUSD',
      'ETCUST',
      'ETH2X:ETH',
      'ETH2X:USD',
      'ETH2X:UST',
      'ETH:XAUT',
      'ETHBTC',
      'ETHEUR',
      'ETHGBP',
      'ETHJPY',
      'ETHUSD',
      'ETHUST',
      'ETHW:USD',
      'ETHW:UST',
      'EURQ:USD',
      'EURQ:UST',
      'EURR:USD',
      'EURR:UST',
      'EURUST',
      'EUTUSD',
      'EUTUST',
      'FETUSD',
      'FETUST',
      'FILUSD',
      'FILUST',
      'FLOKI:USD',
      'FLOKI:UST',
      'FTMUSD',
      'FTMUST',
      'GALA:USD',
      'GALA:UST',
      'GBPUST',
      'GMMT:USD',
      'GMMT:UST',
      'GOMINING:USD',
      'GOMINING:UST',
      'GRTUSD',
      'GRTUST',
      'GTXUSD',
      'GTXUST',
      'HILSV:USD',
      'HIXUSD',
      'HIXUST',
      'HMSTR:USD',
      'HMSTR:UST',
      'HTXDAO:USD',
      'HTXDAO:UST',
      'ICPUSD',
      'ICPUST',
      'IOTBTC',
      'IOTUSD',
      'JASMY:USD',
      'JASMY:UST',
      'JPYUST',
      'JSTUSD',
      'JSTUST',
      'JUPUSD',
      'JUPUST',
      'JUSTICE:USD',
      'JUSTICE:UST',
      'JXXUSD',
      'JXXUST',
      'KANUSD',
      'KANUST',
      'KARATE:USD',
      'KARATE:UST',
      'KAVA:USD',
      'KAVA:UST',
      'KMNO:USD',
      'KMNO:UST',
      'LDOUSD',
      'LDOUST',
      'LEOBTC',
      'LEOETH',
      'LEOUSD',
      'LEOUST',
      'LIFIII:USD',
      'LIFIII:UST',
      'LINK:USD',
      'LINK:UST',
      'LTCBTC',
      'LTCUSD',
      'LTCUST',
      'MANEKI:USD',
      'MANEKI:UST',
      'MATIC:BTC',
      'MATIC:USD',
      'MATIC:UST',
      'MEWUSD',
      'MEWUST',
      'MIMUSD',
      'MIMUST',
      'MKRUSD',
      'MKRUST',
      'MLNUSD',
      'MNAUSD',
      'MPCUSD',
      'MPCUST',
      'MXNT:USD',
      'NEAR:USD',
      'NEAR:UST',
      'NEOUSD',
      'NEOUST',
      'NEXO:BTC',
      'NEXO:USD',
      'NEXO:UST',
      'NOTUSD',
      'NOTUST',
      'NYMUSD',
      'NYMUST',
      'OMGBTC',
      'OMGUSD',
      'OMNUSD',
      'OPXUSD',
      'OPXUST',
      'PEPE:USD',
      'PEPE:UST',
      'PNKUSD',
      'POLUSD',
      'POLUST',
      'RRTUSD',
      'SAND:USD',
      'SAND:UST',
      'SCROLL:USD',
      'SCROLL:UST',
      'SEIUSD',
      'SEIUST',
      'SHIB:USD',
      'SHIB:UST',
      'SOLBTC',
      'SOLUSD',
      'SOLUST',
      'SPEC:USD',
      'SPEC:UST',
      'SPELL:USD',
      'SPELL:UST',
      'STGUSD',
      'STGUST',
      'STRK:USD',
      'STRK:UST',
      'SUIUSD',
      'SUIUST',
      'SUNUSD',
      'SUNUST',
      'SUSHI:USD',
      'SUSHI:UST',
      'SWEAT:USD',
      'SWEAT:UST',
      'TESTADA:TESTUSD',
      'TESTALGO:TESTUSD',
      'TESTAPT:TESTUSD',
      'TESTAVAX:TESTUSD',
      'TESTBTC:TESTUSD',
      'TESTBTC:TESTUSDT',
      'TESTDOGE:TESTUSD',
      'TESTDOT:TESTUSD',
      'TESTEOS:TESTUSD',
      'TESTETH:TESTUSD',
      'TESTFIL:TESTUSD',
      'TESTLTC:TESTUSD',
      'TESTMATIC:TESTUSD',
      'TESTMATIC:TESTUSDT',
      'TESTNEAR:TESTUSD',
      'TESTSOL:TESTUSD',
      'TESTXAUT:TESTUSD',
      'TESTXTZ:TESTUSD',
      'TIAUSD',
      'TIAUST',
      'TITAN1:GBP',
      'TITAN1:USD',
      'TITAN2:GBP',
      'TITAN2:USD',
      'TOKEN:USD',
      'TOKEN:UST',
      'TOMI:USD',
      'TOMI:UST',
      'TONUSD',
      'TONUST',
      'TRXBTC',
      'TRXEUR',
      'TRXUSD',
      'TRXUST',
      'TRYUST',
      'TSDUSD',
      'TSDUST',
      'TURBO:USD',
      'TURBO:UST',
      'UDCUSD',
      'UDCUST',
      'UNIUSD',
      'UNIUST',
      'UOSBTC',
      'UOSUSD',
      'USDQ:USD',
      'USDQ:UST',
      'USDR:USD',
      'USDR:UST',
      'UST:CNHT',
      'UST:MXNT',
      'USTBL:USD',
      'USTBL:UST',
      'USTUSD',
      'UXLINK:USD',
      'UXLINK:UST',
      'VELAR:USD',
      'VELAR:UST',
      'WBTBTC',
      'WBTUSD',
      'WHBT:USD',
      'WHBT:UST',
      'WIFUSD',
      'WIFUST',
      'WILD:USD',
      'WOOUSD',
      'WOOUST',
      'XAUT:BTC',
      'XAUT:USD',
      'XAUT:UST',
      'XDCUSD',
      'XDCUST',
      'XLMBTC',
      'XLMUSD',
      'XLMUST',
      'XMRBTC',
      'XMRUSD',
      'XMRUST',
      'XRDBTC',
      'XRDUSD',
      'XRPBTC',
      'XRPUSD',
      'XRPUST',
      'XTPUSD',
      'XTPUST',
      'XTZUSD',
      'YFIUSD',
      'YFIUST',
      'ZECBTC',
      'ZECUSD',
      'ZKXUSD',
      'ZKXUST',
      'ZROUSD',
      'ZROUST',
      'ZRXUSD'
    ]]
  ],
  [
    'map_symbols',
    [[
      [
        'BTCF0:USTF0',
        'BTC-PERP'
      ],
      [
        'ETHF0:USTF0',
        'ETH-PERP'
      ],
      [
        'AMPF0:USTF0',
        'AMPL-PERP'
      ],
      [
        'XAUTF0:USTF0',
        'XAUT-PERP'
      ],
      [
        'XAGF0:USTF0',
        'XAG-PERP'
      ],
      [
        'EUROPE50IXF0:USTF0',
        'EUROPE50'
      ],
      [
        'GERMANY30IXF0:USTF0',
        'GERMANY30-PERP'
      ],
      [
        'LINKF0:USTF0',
        'LINK-PERP'
      ],
      [
        'DOTF0:USTF0',
        'DOT-PERP'
      ],
      [
        'UNIF0:USTF0',
        'UNI-PERP'
      ],
      [
        'LTCF0:USTF0',
        'LTC-PERP'
      ],
      [
        'IOTF0:USTF0',
        'IOT-PERP'
      ],
      [
        'EOSF0:USTF0',
        'EOS-PERP'
      ],
      [
        'BTCDOMF0:USTF0',
        'BTCDOM-PERP'
      ],
      [
        'EURF0:USTF0',
        'EUR-PERP'
      ],
      [
        'JPYF0:USTF0',
        'JPY-PERP'
      ],
      [
        'GBPF0:USTF0',
        'GBP-PERP'
      ],
      [
        'ETHF0:BTCF0',
        'ETH/BTC-PERP'
      ],
      [
        'ADAF0:USTF0',
        'ADA-PERP'
      ],
      [
        'XLMF0:USTF0',
        'XLM-PERP'
      ],
      [
        'LTCF0:BTCF0',
        'LTC/BTC-PERP'
      ],
      [
        'DOTF0:BTCF0',
        'DOT/BTC-PERP'
      ],
      [
        'XAUTF0:BTCF0',
        'XAUT/BTC-PERP'
      ],
      [
        'DOGEF0:USTF0',
        'DOGE-PERP'
      ],
      [
        'SOLF0:USTF0',
        'SOL-PERP'
      ],
      [
        'SUSHIF0:USTF0',
        'SUSHI-PERP'
      ],
      [
        'AVAXF0:USTF0',
        'AVAX-PERP'
      ],
      [
        'FILF0:USTF0',
        'FIL-PERP'
      ],
      [
        'XMRF0:USTF0',
        'XMR-PERP'
      ],
      [
        'XRPF0:USTF0',
        'XRP-PERP'
      ],
      [
        'XRPF0:BTCF0',
        'XRP/BTC-PERP'
      ],
      [
        'ALGF0:USTF0',
        'ALGO-PERP'
      ],
      [
        'GERMANY40IXF0:USTF0',
        'GERMANY40'
      ],
      [
        'AAVEF0:USTF0',
        'AAVE-PERP'
      ],
      [
        'MATICF0:USTF0',
        'MATIC-PERP'
      ],
      [
        'FTMF0:USTF0',
        'FTM-PERP'
      ],
      [
        'EGLDF0:USTF0',
        'EGLD-PERP'
      ],
      [
        'AXSF0:USTF0',
        'AXS-PERP'
      ],
      [
        'COMPF0:USTF0',
        'COMP-PERP'
      ],
      [
        'XTZF0:USTF0',
        'XTZ-PERP'
      ],
      [
        'TRXF0:USTF0',
        'TRX-PERP'
      ],
      [
        'ATOF0:USTF0',
        'ATOM-PERP'
      ],
      [
        'SOLF0:BTCF0',
        'SOL/BTC-PERP'
      ],
      [
        'AVAXF0:BTCF0',
        'AVAX/BTC-PERP'
      ],
      [
        'SHIBF0:USTF0',
        'SHIB-PERP'
      ],
      [
        'OMGF0:USTF0',
        'OMG-PERP'
      ],
      [
        'BTCF0:EUTF0',
        'BTC/EURt-PERP'
      ],
      [
        'ETHF0:EUTF0',
        'ETH/EURt-PERP'
      ],
      [
        'ZECF0:USTF0',
        'ZEC-PERP'
      ],
      [
        'NEOF0:USTF0',
        'NEO-PERP'
      ],
      [
        'CRVF0:USTF0',
        'CRV-PERP'
      ],
      [
        'ICPF0:USTF0',
        'ICP-PERP'
      ],
      [
        'NEARF0:USTF0',
        'NEAR-PERP'
      ],
      [
        'APEF0:USTF0',
        'APE-PERP'
      ],
      [
        'GALAF0:USTF0',
        'GALA-PERP'
      ],
      [
        'ETCF0:USTF0',
        'ETC-PERP'
      ],
      [
        'ANCF0:USTF0',
        'ANC-PERP'
      ],
      [
        'WAVESF0:USTF0',
        'WAVES-PERP'
      ],
      [
        'JASMYF0:USTF0',
        'JASMY-PERP'
      ],
      [
        'KNCF0:USTF0',
        'KNC-PERP'
      ],
      [
        'STGF0:USTF0',
        'STG-PERP'
      ],
      [
        'MKRF0:USTF0',
        'MKR-PERP'
      ],
      [
        'SANDF0:USTF0',
        'SAND-PERP'
      ],
      [
        'APTF0:USTF0',
        'APT-PERP'
      ],
      [
        'UKOILF0:USTF0',
        'UKOIL-PERP'
      ],
      [
        'XPDF0:USTF0',
        'XPD-PERP'
      ],
      [
        'XPTF0:USTF0',
        'XPT-PERP'
      ],
      [
        'ARBF0:USTF0',
        'ARB-PERP'
      ],
      [
        'FRANCE40IXF0:USTF0',
        'FRANCE40'
      ],
      [
        'SPAIN35IXF0:USTF0',
        'SPAIN35'
      ],
      [
        'UK100IXF0:USTF0',
        'UK100'
      ],
      [
        'TESTBTCF0:TESTUSDTF0',
        'BTC-PERP'
      ],
      [
        'TESTMATICF0:TESTUSDTF0',
        'MATIC-PERP'
      ],
      [
        'TESTDOTF0:TESTUSDTF0',
        'DOT-PERP'
      ],
      [
        'TESTSOLF0:TESTUSDTF0',
        'SOL-PERP'
      ],
      [
        'JAPAN225IXF0:USTF0',
        'JAPAN225'
      ],
      [
        'HONGKONG50IXF0:USTF0',
        'HONGKONG50'
      ],
      [
        'AUSTRALIA200IXF0:USTF0',
        'AUSTRALIA200'
      ],
      [
        'TESTXAUTF0:TESTUSDTF0',
        'XAUT-PERP'
      ],
      [
        'TESTETHF0:TESTUSDTF0',
        'ETH-PERP'
      ],
      [
        'TESTAVAXF0:TESTUSDTF0',
        'AVAX-PERP'
      ],
      [
        'TESTDOGEF0:TESTUSDTF0',
        'DOGE-PERP'
      ],
      [
        'TESTXTZF0:TESTUSDTF0',
        'XTZ-PERP'
      ],
      [
        'TESTALGOF0:TESTUSDTF0',
        'ALGO-PERP'
      ],
      [
        'TESTNEARF0:TESTUSDTF0',
        'NEAR-PERP'
      ],
      [
        'TESTFILF0:TESTUSDTF0',
        'FIL-PERP'
      ],
      [
        'TESTADAF0:TESTUSDTF0',
        'ADA-PERP'
      ],
      [
        'TESTLTCF0:TESTUSDTF0',
        'LTC-PERP'
      ],
      [
        'TESTAPTF0:TESTUSDTF0',
        'APT-PERP'
      ],
      [
        'TESTEOSF0:TESTUSDTF0',
        'EOS-PERP'
      ],
      [
        'TRYF0:USTF0',
        'TRY-PERP'
      ],
      [
        'BNBF0:USTF0',
        'BNB-PERP'
      ],
      [
        'WLDF0:USTF0',
        'WLD-PERP'
      ],
      [
        'BVIVF0:USTF0',
        'BVIV-PERP'
      ],
      [
        'EVIVF0:USTF0',
        'EVIV-PERP'
      ],
      [
        'CHZF0:USTF0',
        'CHZ-PERP'
      ],
      [
        'POLF0:USTF0',
        'POL-PERP'
      ],
      [
        'PEPEF0:USTF0',
        'PEPE-PERP'
      ],
      [
        'SUIF0:USTF0',
        'SUI-PERP'
      ],
      [
        'TONF0:USTF0',
        'TON-PERP'
      ]
    ]]
  ],
  [
    'inactive_currencies',
    [[
      'AAA',
      'ABS',
      'ADD',
      'AGI',
      'AID',
      'AIO',
      'AIX',
      'ALBT',
      'AMPF0',
      'ANC',
      'ANCF0',
      'ANT',
      'APP',
      'AST',
      'ATD',
      'ATLAS',
      'ATM',
      'AUC',
      'AVT',
      'B21X',
      'BAB',
      'BAND',
      'BAT',
      'BBB',
      'BBN',
      'BCC',
      'BCHABC',
      'BCI',
      'BCU',
      'BFT',
      'BMI',
      'BNT',
      'BOBA',
      'BOO',
      'BOX',
      'BRISE',
      'BSV',
      'BT1',
      'BT2',
      'BTG',
      'BTSE',
      'CBT',
      'CEL',
      'CFI',
      'CHSB',
      'CLO',
      'CND',
      'CNN',
      'CONV',
      'CSTBCHABC',
      'CSTBCHN',
      'CSX',
      'CTK',
      'CTX',
      'DAD',
      'DAPP',
      'DAT',
      'DCR',
      'DGB',
      'DGX',
      'DOG',
      'DORA',
      'DRN',
      'DTA',
      'DTH',
      'DTX',
      'DUSK',
      'DVF',
      'EDO',
      'ELF',
      'ENJ',
      'EOSDT',
      'EOX',
      'ESS',
      'ETP',
      'EUS',
      'EVT',
      'EXO',
      'FBT',
      'FCL',
      'FOA',
      'FSN',
      'FTMF0',
      'FTT',
      'FUN',
      'GEN',
      'GERMANY30IXF0',
      'GMT',
      'GNT',
      'GOC',
      'GOT',
      'GPT',
      'GSD',
      'GST',
      'GXT',
      'HEC',
      'HEZ',
      'HMT',
      'HMTPLG',
      'HOT',
      'HTX',
      'ICE',
      'IDX',
      'IMP',
      'INT',
      'IOS',
      'IQX',
      'KAI',
      'KNC',
      'KNCF0',
      'KSM',
      'LAI',
      'LOO',
      'LRC',
      'LUNA',
      'LUXO',
      'MAN',
      'MATICF0',
      'MATICM',
      'MEME',
      'MGO',
      'MIR',
      'MIT',
      'MOB',
      'MSC',
      'MTN',
      'MTO',
      'NCA',
      'NEC',
      'NIO',
      'NOM',
      'NUT',
      'NXRA',
      'OCEAN',
      'ODE',
      'OGN',
      'OKB',
      'ONE',
      'ONL',
      'ONUS',
      'ORS',
      'OXY',
      'PAI',
      'PANTEOS',
      'PAS',
      'PBALEOS',
      'PBANDEOS',
      'PBATEOS',
      'PBTCEOS',
      'PBTCETH',
      'PCOMPEOS',
      'PDAIEOS',
      'PEOSETH',
      'PETHEOS',
      'PLANETS',
      'PLINKEOS',
      'PLRCEOS',
      'PLTCEOS',
      'PLTCETH',
      'PMKREOS',
      'PNG',
      'POA',
      'POLC',
      'POLIS',
      'POMGEOS',
      'POY',
      'PPNKEOS',
      'PPNTEOS',
      'PREPEOS',
      'PRMX',
      'PSNXEOS',
      'PUNIEOS',
      'PUOSEOS',
      'PYFIEOS',
      'PZRXEOS',
      'QRDO',
      'QSH',
      'QTF',
      'RBT',
      'RCN',
      'RDN',
      'REEF',
      'REP',
      'REQ',
      'RIF',
      'RINGX',
      'RLC',
      'ROSE',
      'RRB',
      'RTE',
      'SAN',
      'SCR',
      'SEE',
      'SEN',
      'SENATE',
      'SGB',
      'SHFT',
      'SHFTM',
      'SIDUS',
      'SMR',
      'SNG',
      'SNT',
      'SPK',
      'SRM',
      'STJ',
      'SWM',
      'SXX',
      'TENET',
      'TERRAUST',
      'TESTMATICF0',
      'TH1',
      'THETA',
      'TKN',
      'TNB',
      'TREEB',
      'TRI',
      'TST',
      'UFR',
      'UOP',
      'USDTDVF',
      'USDTHEZ',
      'USDTOMG',
      'USK',
      'UTK',
      'UTN',
      'VEE',
      'VELO',
      'VEN',
      'VLD',
      'VRA',
      'VSY',
      'WAX',
      'WLO',
      'WMINIMA',
      'WPR',
      'WTC',
      'XCAD',
      'XCH',
      'XCN',
      'XRA',
      'XSN',
      'YGG',
      'YYW',
      'ZBT',
      'ZCN',
      'ZIL',
      'ZMT'
    ]]
  ],
  [
    'margin_currencies',
    [[
      'ADA',
      'ALG',
      'AMP',
      'APE',
      'APT',
      'ATO',
      'AVAX',
      'BCHN',
      'BTC',
      'COMP',
      'DAI',
      'DOGE',
      'DOT',
      'DSH',
      'EGLD',
      'EOS',
      'ETC',
      'ETH',
      'ETHW',
      'EUR',
      'FIL',
      'FTM',
      'GBP',
      'IOT',
      'JPY',
      'LEO',
      'LINK',
      'LTC',
      'MATIC',
      'MKR',
      'MXNT',
      'NEO',
      'SHIB',
      'SOL',
      'SUSHI',
      'TESTADA',
      'TESTALGO',
      'TESTAPT',
      'TESTAVAX',
      'TESTBTC',
      'TESTDOGE',
      'TESTDOT',
      'TESTEOS',
      'TESTETH',
      'TESTFIL',
      'TESTLTC',
      'TESTMATIC',
      'TESTNEAR',
      'TESTSOL',
      'TESTUSD',
      'TESTUSDT',
      'TESTXAUT',
      'TESTXTZ',
      'TRX',
      'TRY',
      'UNI',
      'USD',
      'UST',
      'XAUT',
      'XLM',
      'XMR',
      'XRP',
      'ZEC',
      'ZRX'
    ]]
  ],
  [
    'inactive_symbols',
    [[
      'AAABBB',
      'ABSETH',
      'ABSUSD',
      'AGIBTC',
      'AGIETH',
      'AGIUSD',
      'AIDBTC',
      'AIDETH',
      'AIDUSD',
      'AIOBTC',
      'AIOETH',
      'AIOUSD',
      'AIOZ:UST',
      'AIXUSD',
      'AIXUST',
      'ALBT:USD',
      'ALBT:UST',
      'ALGBTC',
      'ALGUST',
      'AMPBTC',
      'AMPF0:USTF0',
      'ANCF0:USTF0',
      'ANCUSD',
      'ANCUST',
      'ANTBTC',
      'ANTETH',
      'ANTUSD',
      'APENFT:UST',
      'APPUSD',
      'APPUST',
      'ASTETH',
      'ASTUSD',
      'ATLAS:USD',
      'ATLAS:UST',
      'ATMBTC',
      'ATMETH',
      'ATMUSD',
      'ATOBTC',
      'ATOETH',
      'AUCBTC',
      'AUCETH',
      'AUCUSD',
      'AVAXF0:BTCF0',
      'AVTBTC',
      'AVTETH',
      'AVTUSD',
      'AXSUSD',
      'AXSUST',
      'B21X:USD',
      'B21X:UST',
      'BABBTC',
      'BABUSD',
      'BABUST',
      'BALUSD',
      'BALUST',
      'BAND:USD',
      'BAND:UST',
      'BATBTC',
      'BATETH',
      'BATUSD',
      'BATUST',
      'BCHABC:USD',
      'BCHBTC',
      'BCHETH',
      'BCHUSD',
      'BFTBTC',
      'BFTETH',
      'BFTUSD',
      'BLUR:USD',
      'BLUR:UST',
      'BMIUSD',
      'BMIUST',
      'BMNBTC',
      'BMNUSD',
      'BNTBTC',
      'BNTETH',
      'BNTUSD',
      'BOBA:USD',
      'BOBA:UST',
      'BOOUSD',
      'BOOUST',
      'BORG:BTC',
      'BORG:USD',
      'BORG:UST',
      'BOSON:USD',
      'BOSON:UST',
      'BOXETH',
      'BOXUSD',
      'BRISE:USD',
      'BRISE:UST',
      'BSVBTC',
      'BSVUSD',
      'BTC:CNHT',
      'BTC:MXNT',
      'BTCEUT',
      'BTCF0:EUTF0',
      'BTCMIM',
      'BTCXCH',
      'BTGBTC',
      'BTGUSD',
      'BTSE:USD',
      'CBTBTC',
      'CBTETH',
      'CBTUSD',
      'CCDBTC',
      'CELUSD',
      'CELUST',
      'CHSB:BTC',
      'CHSB:USD',
      'CHSB:UST',
      'CLOBTC',
      'CLOUSD',
      'CNDBTC',
      'CNDETH',
      'CNDUSD',
      'CNH:CNHT',
      'CNNETH',
      'CNNUSD',
      'CONV:USD',
      'CONV:UST',
      'COQUSD',
      'COQUST',
      'CSXETH',
      'CSXUSD',
      'CTKUSD',
      'CTKUST',
      'CTXBTC',
      'CTXETH',
      'CTXUSD',
      'DADBTC',
      'DADETH',
      'DADUSD',
      'DAIBTC',
      'DAIETH',
      'DAPP:USD',
      'DAPP:UST',
      'DATBTC',
      'DATETH',
      'DATUSD',
      'DCRUSD',
      'DGBUSD',
      'DGXETH',
      'DGXUSD',
      'DOGBTC',
      'DOGUSD',
      'DOGUST',
      'DORA:USD',
      'DORA:UST',
      'DOTBTC',
      'DOTF0:BTCF0',
      'DRNETH',
      'DRNUSD',
      'DTABTC',
      'DTAETH',
      'DTAUSD',
      'DTHBTC',
      'DTHETH',
      'DTHUSD',
      'DTXUSD',
      'DTXUST',
      'DUSK:BTC',
      'DUSK:USD',
      'DVFUSD',
      'DVFUST',
      'EDOBTC',
      'EDOETH',
      'EDOUSD',
      'ELFBTC',
      'ELFETH',
      'ELFUSD',
      'ENJETH',
      'ENJUSD',
      'EOSDT:USD',
      'EOSDT:UST',
      'EOSETH',
      'EOSEUR',
      'EOSGBP',
      'EOSJPY',
      'ESSBTC',
      'ESSETH',
      'ESSUSD',
      'ETH:MXNT',
      'ETHEUT',
      'ETHF0:EUTF0',
      'ETHS:USD',
      'ETPBTC',
      'ETPETH',
      'ETPUSD',
      'EUSBTC',
      'EUSETH',
      'EUSUSD',
      'EUT:MXNT',
      'EUTEUR',
      'EXOUSD',
      'EXRD:BTC',
      'EXRD:USD',
      'FBTUSD',
      'FBTUST',
      'FCLUSD',
      'FCLUST',
      'FLRUSD',
      'FLRUST',
      'FOAETH',
      'FOAUSD',
      'FORTH:USD',
      'FORTH:UST',
      'FSNBTC',
      'FSNETH',
      'FSNUSD',
      'FTMF0:USTF0',
      'FTTUSD',
      'FTTUST',
      'FUNBTC',
      'FUNUSD',
      'GBPEUT',
      'GENETH',
      'GENUSD',
      'GERMANY30IXF0:USTF0',
      'GMTUSD',
      'GMTUST',
      'GNOETH',
      'GNOUSD',
      'GNTBTC',
      'GNTETH',
      'GNTUSD',
      'GOCUSD',
      'GOCUST',
      'GOTETH',
      'GOTEUR',
      'GOTUSD',
      'GPTUSD',
      'GPTUST',
      'GSDUSD',
      'GSTUSD',
      'GSTUST',
      'GXTUSD',
      'GXTUST',
      'HECUSD',
      'HECUST',
      'HEZUSD',
      'HEZUST',
      'HIXBTC',
      'HMTUSD',
      'HMTUST',
      'HOTBTC',
      'HOTETH',
      'HOTUSD',
      'HTXUSD',
      'HTXUST',
      'ICEUSD',
      'ICPBTC',
      'IDXBTC',
      'IDXUSD',
      'IDXUST',
      'IMPETH',
      'IMPUSD',
      'INJUSD',
      'INJUST',
      'INTETH',
      'INTUSD',
      'IOSBTC',
      'IOSETH',
      'IOSUSD',
      'IOTETH',
      'IOTEUR',
      'IOTGBP',
      'IOTJPY',
      'IQXBTC',
      'IQXUSD',
      'IQXUST',
      'JSTBTC',
      'KAIUSD',
      'KAIUST',
      'KNCBTC',
      'KNCETH',
      'KNCF0:USTF0',
      'KNCUSD',
      'KSMUSD',
      'KSMUST',
      'LAIUSD',
      'LAIUST',
      'LEOEOS',
      'LOOETH',
      'LOOUSD',
      'LRCBTC',
      'LRCETH',
      'LRCUSD',
      'LUNA2:USD',
      'LUNA2:UST',
      'LUNA:BTC',
      'LUNA:ETH',
      'LUNA:USD',
      'LUNA:UST',
      'LUNAF0:BTCF0',
      'LUNAF0:USTF0',
      'LUXO:USD',
      'LYMBTC',
      'LYMETH',
      'LYMUSD',
      'LYMUST',
      'MANETH',
      'MANUSD',
      'MATICF0:USTF0',
      'MEME:USD',
      'MEME:UST',
      'MGOETH',
      'MGOUSD',
      'MIRUSD',
      'MIRUST',
      'MITBTC',
      'MITETH',
      'MITUSD',
      'MKRBTC',
      'MKRDAI',
      'MKRETH',
      'MLNETH',
      'MNABTC',
      'MNAETH',
      'MOBUSD',
      'MOBUST',
      'MODE:USD',
      'MODE:UST',
      'MTNBTC',
      'MTNETH',
      'MTNUSD',
      'NCABTC',
      'NCAETH',
      'NCAUSD',
      'NECBTC',
      'NECETH',
      'NECUSD',
      'NEOBTC',
      'NEOETH',
      'NEOEUR',
      'NEOGBP',
      'NEOJPY',
      'NIOETH',
      'NIOUSD',
      'NOMUSD',
      'NOMUST',
      'NUTUSD',
      'NUTUST',
      'NXRA:USD',
      'OCEAN:USD',
      'OCEAN:UST',
      'ODEBTC',
      'ODEETH',
      'ODEUSD',
      'OGNUSD',
      'OGNUST',
      'OKBBTC',
      'OKBETH',
      'OKBUSD',
      'OKBUST',
      'OMGDAI',
      'OMGETH',
      'OMGF0:USTF0',
      'OMNBTC',
      'ONEUSD',
      'ONEUST',
      'ONLETH',
      'ONLUSD',
      'ORSBTC',
      'ORSETH',
      'ORSUSD',
      'OXYUSD',
      'OXYUST',
      'PAIBTC',
      'PAIUSD',
      'PASETH',
      'PASUSD',
      'PAXUSD',
      'PAXUST',
      'PLANETS:USD',
      'PLANETS:UST',
      'PLUUSD',
      'PNGUSD',
      'PNGUST',
      'PNKETH',
      'POABTC',
      'POAETH',
      'POAUSD',
      'POLC:BTC',
      'POLC:USD',
      'POLC:UST',
      'POLIS:USD',
      'POLIS:UST',
      'PORTAL:USD',
      'PORTAL:UST',
      'POYBTC',
      'POYETH',
      'POYUSD',
      'PRMX:USD',
      'PRMX:UST',
      'QRDO:USD',
      'QRDO:UST',
      'QSHBTC',
      'QSHETH',
      'QSHUSD',
      'QTFBTC',
      'QTFUSD',
      'QTMBTC',
      'QTMETH',
      'QTMUSD',
      'RBTBTC',
      'RBTUSD',
      'RCNBTC',
      'RCNETH',
      'RCNUSD',
      'RDNBTC',
      'RDNETH',
      'RDNUSD',
      'REEF:USD',
      'REEF:UST',
      'REPBTC',
      'REPETH',
      'REPUSD',
      'REQBTC',
      'REQETH',
      'REQUSD',
      'RIFBTC',
      'RIFUSD',
      'RINGX:USD',
      'RLCBTC',
      'RLCETH',
      'RLCUSD',
      'RLYUSD',
      'RLYUST',
      'ROSE:USD',
      'ROSE:UST',
      'RRBUSD',
      'RRBUST',
      'RRTBTC',
      'RTEETH',
      'RTEUSD',
      'SANBTC',
      'SANETH',
      'SANUSD',
      'SCRETH',
      'SCRUSD',
      'SEEBTC',
      'SEEETH',
      'SEEUSD',
      'SENATE:USD',
      'SENATE:UST',
      'SENBTC',
      'SENETH',
      'SENUSD',
      'SGBUSD',
      'SGBUST',
      'SHFT:BTC',
      'SHFT:USD',
      'SHFT:UST',
      'SIDUS:USD',
      'SIDUS:UST',
      'SMRUSD',
      'SMRUST',
      'SNGBTC',
      'SNGETH',
      'SNGUSD',
      'SNTETH',
      'SNTUSD',
      'SNXUSD',
      'SNXUST',
      'SOLF0:BTCF0',
      'SPELL:MIM',
      'SPKBTC',
      'SPKETH',
      'SPKUSD',
      'SRMUSD',
      'SRMUST',
      'STJBTC',
      'STJETH',
      'STJUSD',
      'SUKU:USD',
      'SUKU:UST',
      'SWMETH',
      'SWMUSD',
      'SXXUSD',
      'SXXUST',
      'TAIKO:USD',
      'TAIKO:UST',
      'TENET:USD',
      'TENET:UST',
      'TERRAUST:USD',
      'TERRAUST:UST',
      'TESTMATICF0:TESTUSDTF0',
      'THETA:USD',
      'THETA:UST',
      'TKNETH',
      'TKNUSD',
      'TLOS:USD',
      'TLOS:UST',
      'TNBBTC',
      'TNBETH',
      'TNBUSD',
      'TRADE:USD',
      'TRADE:UST',
      'TREEB:USD',
      'TREEB:UST',
      'TRIETH',
      'TRIUSD',
      'TRXETH',
      'TRXJPY',
      'UFRETH',
      'UFRUSD',
      'UOPUSD',
      'UOPUST',
      'USKBTC',
      'USKEOS',
      'USKETH',
      'USKUSD',
      'USKUST',
      'UTKBTC',
      'UTKETH',
      'UTKUSD',
      'UTNETH',
      'UTNUSD',
      'VEEBTC',
      'VEEETH',
      'VEEUSD',
      'VELO:USD',
      'VELO:UST',
      'VENBTC',
      'VENETH',
      'VENUSD',
      'VETBTC',
      'VETETH',
      'VETUSD',
      'VETUST',
      'VLDETH',
      'VLDUSD',
      'VRAUSD',
      'VRAUST',
      'VSYBTC',
      'VSYUSD',
      'WAVES:USD',
      'WAVES:UST',
      'WAVESF0:USTF0',
      'WAXETH',
      'WAXUSD',
      'WBTETH',
      'WILD:UST',
      'WLDF0:USTF0',
      'WLOXLM',
      'WMINIMA:USD',
      'WMINIMA:UST',
      'WNCG:USD',
      'WNCG:UST',
      'WPRBTC',
      'WPRETH',
      'WPRUSD',
      'WTCETH',
      'WTCUSD',
      'WXXUSD',
      'WXXUST',
      'XCAD:USD',
      'XCHETH',
      'XCHUSD',
      'XCNUSD',
      'XCNUST',
      'XLMETH',
      'XLMJPY',
      'XRAETH',
      'XRAUSD',
      'XSNUSD',
      'XTZBTC',
      'XTZUST',
      'XVGETH',
      'XVGEUR',
      'XVGGBP',
      'XVGJPY',
      'XVGUSD',
      'YGGETH',
      'YGGUSD',
      'YYWBTC',
      'YYWETH',
      'YYWUSD',
      'ZBTUSD',
      'ZBTUST',
      'ZCNBTC',
      'ZCNETH',
      'ZCNUSD',
      'ZETA:USD',
      'ZETA:UST',
      'ZILBTC',
      'ZILETH',
      'ZILUSD',
      'ZMTUSD',
      'ZMTUST',
      'ZRXBTC',
      'ZRXDAI',
      'ZRXETH'
    ]]
  ],
  [
    'futures',
    [[
      'AAVEF0:USTF0',
      'ADAF0:USTF0',
      'ALGF0:USTF0',
      'APEF0:USTF0',
      'APTF0:USTF0',
      'ARBF0:USTF0',
      'ATOF0:USTF0',
      'AUSTRALIA200IXF0:USTF0',
      'AVAXF0:USTF0',
      'AXSF0:USTF0',
      'BNBF0:USTF0',
      'BTCDOMF0:USTF0',
      'BTCF0:USTF0',
      'BVIVF0:USTF0',
      'CHZF0:USTF0',
      'COMPF0:USTF0',
      'CRVF0:USTF0',
      'DOGEF0:USTF0',
      'DOTF0:USTF0',
      'EGLDF0:USTF0',
      'EOSF0:USTF0',
      'ETCF0:USTF0',
      'ETHF0:BTCF0',
      'ETHF0:USTF0',
      'EURF0:USTF0',
      'EUROPE50IXF0:USTF0',
      'EVIVF0:USTF0',
      'FILF0:USTF0',
      'FRANCE40IXF0:USTF0',
      'GALAF0:USTF0',
      'GBPF0:USTF0',
      'GERMANY40IXF0:USTF0',
      'HONGKONG50IXF0:USTF0',
      'ICPF0:USTF0',
      'IOTF0:USTF0',
      'JAPAN225IXF0:USTF0',
      'JASMYF0:USTF0',
      'JPYF0:USTF0',
      'LINKF0:USTF0',
      'LTCF0:BTCF0',
      'LTCF0:USTF0',
      'MKRF0:USTF0',
      'NEARF0:USTF0',
      'NEOF0:USTF0',
      'PEPEF0:USTF0',
      'POLF0:USTF0',
      'SANDF0:USTF0',
      'SHIBF0:USTF0',
      'SOLF0:USTF0',
      'SPAIN35IXF0:USTF0',
      'STGF0:USTF0',
      'SUIF0:USTF0',
      'SUSHIF0:USTF0',
      'TESTADAF0:TESTUSDTF0',
      'TESTALGOF0:TESTUSDTF0',
      'TESTAPTF0:TESTUSDTF0',
      'TESTAVAXF0:TESTUSDTF0',
      'TESTBTCF0:TESTUSDTF0',
      'TESTDOGEF0:TESTUSDTF0',
      'TESTDOTF0:TESTUSDTF0',
      'TESTEOSF0:TESTUSDTF0',
      'TESTETHF0:TESTUSDTF0',
      'TESTFILF0:TESTUSDTF0',
      'TESTLTCF0:TESTUSDTF0',
      'TESTNEARF0:TESTUSDTF0',
      'TESTSOLF0:TESTUSDTF0',
      'TESTXAUTF0:TESTUSDTF0',
      'TESTXTZF0:TESTUSDTF0',
      'TONF0:USTF0',
      'TRXF0:USTF0',
      'TRYF0:USTF0',
      'UK100IXF0:USTF0',
      'UKOILF0:USTF0',
      'UNIF0:USTF0',
      'XAGF0:USTF0',
      'XAUTF0:BTCF0',
      'XAUTF0:USTF0',
      'XLMF0:USTF0',
      'XMRF0:USTF0',
      'XPDF0:USTF0',
      'XPTF0:USTF0',
      'XRPF0:BTCF0',
      'XRPF0:USTF0',
      'XTZF0:USTF0',
      'ZECF0:USTF0'
    ]]
  ],
  [
    'currencies',
    [[
      '1INCH',
      'AAVE',
      'AAVEF0',
      'ADA',
      'ADAF0',
      'AIOZ',
      'ALG',
      'ALGF0',
      'ALT11M2507',
      'ALT11M250830',
      'ALT11M251029',
      'ALT2612',
      'AMP',
      'APE',
      'APEF0',
      'APENFT',
      'APT',
      'APTF0',
      'ARB',
      'ARBETH',
      'ARBF0',
      'ATH',
      'ATO',
      'ATOF0',
      'AUSDT',
      'AUSTRALIA200IXF0',
      'AVAX',
      'AVAXC',
      'AVAXF0',
      'AXS',
      'AXSF0',
      'AZERO',
      'B2M',
      'BAL',
      'BCH',
      'BCHN',
      'BEST',
      'BFX',
      'BG1',
      'BG2',
      'BGB',
      'BLAST',
      'BLASTETH',
      'BLUR',
      'BMN',
      'BNBF0',
      'BONK',
      'BORG',
      'BOSON',
      'BTC',
      'BTCDOMF0',
      'BTCF0',
      'BTT',
      'BVIVF0',
      'BXN',
      'CAD',
      'CCD',
      'CELO',
      'CHEX',
      'CHF',
      'CHZ',
      'CHZF0',
      'CNH',
      'CNHT',
      'COMP',
      'COMPF0',
      'COQ',
      'CRV',
      'CRVF0',
      'DAI',
      'DOGE',
      'DOGEF0',
      'DOP',
      'DOT',
      'DOTF0',
      'DRK',
      'DSH',
      'DYM',
      'EGLD',
      'EGLDF0',
      'EIGEN',
      'ENA',
      'ENYM',
      'EOS',
      'EOSF0',
      'ETC',
      'ETCF0',
      'ETH',
      'ETH2P',
      'ETH2R',
      'ETH2U',
      'ETH2X',
      'ETHF0',
      'ETHS',
      'ETHW',
      'EUR',
      'EURF0',
      'EUROPE50IXF0',
      'EURQ',
      'EURR',
      'EUT',
      'EUTF0',
      'EVIVF0',
      'EXRD',
      'FET',
      'FIL',
      'FILF0',
      'FLOKI',
      'FLR',
      'FORTH',
      'FRANCE40IXF0',
      'FTM',
      'GALA',
      'GALAF0',
      'GBP',
      'GBPF0',
      'GERMANY40IXF0',
      'GMMT',
      'GNO',
      'GOMINING',
      'GRT',
      'GTX',
      'HILSV',
      'HIX',
      'HKD',
      'HMSTR',
      'HONGKONG50IXF0',
      'HTXDAO',
      'ICP',
      'ICPF0',
      'INJ',
      'IOT',
      'IOTF0',
      'JAPAN225IXF0',
      'JASMY',
      'JASMYF0',
      'JPY',
      'JPYF0',
      'JST',
      'JUP',
      'JUSTICE',
      'JXX',
      'KAN',
      'KARATE',
      'KAVA',
      'KMNO',
      'LBT',
      'LDO',
      'LEO',
      'LES',
      'LET',
      'LIFIII',
      'LINK',
      'LINKF0',
      'LNX',
      'LTC',
      'LTCF0',
      'LUNA2',
      'LUNAF0',
      'LYM',
      'MANEKI',
      'MATIC',
      'MEW',
      'MIM',
      'MKR',
      'MKRF0',
      'MLN',
      'MNA',
      'MODE',
      'MODEETH',
      'MPC',
      'MXNT',
      'NEAR',
      'NEARF0',
      'NEO',
      'NEOF0',
      'NEOGAS',
      'NEXO',
      'NOT',
      'NYM',
      'OMG',
      'OMGF0',
      'OMN',
      'OPX',
      'OPXETH',
      'PAX',
      'PEPE',
      'PEPEF0',
      'PLU',
      'PNK',
      'POL',
      'POLF0',
      'POLM',
      'PORTAL',
      'QTM',
      'RLY',
      'RRT',
      'SAND',
      'SANDF0',
      'SCROLL',
      'SCROLLETH',
      'SEI',
      'SGD',
      'SHIB',
      'SHIBF0',
      'SNX',
      'SOL',
      'SOLF0',
      'SPAIN35IXF0',
      'SPEC',
      'SPELL',
      'STG',
      'STGF0',
      'STRK',
      'SUI',
      'SUIF0',
      'SUKU',
      'SUN',
      'SUSHI',
      'SUSHIF0',
      'SWEAT',
      'SWEATNEP',
      'TAIKO',
      'TAIKOETH',
      'TESTADA',
      'TESTADAF0',
      'TESTALGO',
      'TESTALGOF0',
      'TESTAPT',
      'TESTAPTF0',
      'TESTAVAX',
      'TESTAVAXF0',
      'TESTBTC',
      'TESTBTCF0',
      'TESTDOGE',
      'TESTDOGEF0',
      'TESTDOT',
      'TESTDOTF0',
      'TESTEOS',
      'TESTEOSF0',
      'TESTETH',
      'TESTETHF0',
      'TESTFIL',
      'TESTFILF0',
      'TESTLTC',
      'TESTLTCF0',
      'TESTMATIC',
      'TESTNEAR',
      'TESTNEARF0',
      'TESTSOL',
      'TESTSOLF0',
      'TESTUSD',
      'TESTUSDT',
      'TESTUSDTF0',
      'TESTXAUT',
      'TESTXAUTF0',
      'TESTXTZ',
      'TESTXTZF0',
      'THB',
      'TIA',
      'TITAN1',
      'TITAN2',
      'TLOS',
      'TOKEN',
      'TOMI',
      'TON',
      'TONF0',
      'TRADE',
      'TRX',
      'TRXF0',
      'TRY',
      'TRYF0',
      'TSD',
      'TURBO',
      'TWD',
      'UDC',
      'UK100IXF0',
      'UKOILF0',
      'UNI',
      'UNIF0',
      'UOS',
      'USD',
      'USDQ',
      'USDR',
      'UST',
      'USTBL',
      'USTF0',
      'UXLINK',
      'VELAR',
      'VET',
      'WAVES',
      'WAVESF0',
      'WBT',
      'WHBT',
      'WIF',
      'WILD',
      'WLDF0',
      'WNCG',
      'WOO',
      'WXX',
      'XAGF0',
      'XAUT',
      'XAUTF0',
      'XDC',
      'XLM',
      'XLMF0',
      'XMR',
      'XMRF0',
      'XPDF0',
      'XPTF0',
      'XRD',
      'XRP',
      'XRPF0',
      'XTP',
      'XTZ',
      'XTZF0',
      'XVG',
      'YFI',
      'ZEC',
      'ZECF0',
      'ZETA',
      'ZKETH',
      'ZKX',
      'ZKXETH',
      'ZRO',
      'ZRX'
    ],
    [
      [
        'ALG',
        'ALGO'
      ],
      [
        'AMP',
        'AMPL'
      ],
      [
        'ATO',
        'ATOM'
      ],
      [
        'AUSDT',
        'aUSDT'
      ],
      [
        'BTCF0',
        'BTC'
      ],
      [
        'CHZF0',
        'CHZ'
      ],
      [
        'CNHT',
        'CNHt'
      ],
      [
        'DSH',
        'DASH'
      ],
      [
        'ETH2P',
        'ETH2Pending'
      ],
      [
        'ETH2R',
        'ETH2Rewards'
      ],
      [
        'ETH2U',
        'ETH2Unstaking'
      ],
      [
        'ETH2X',
        'ETH2'
      ],
      [
        'EUT',
        'EURt'
      ],
      [
        'EUTF0',
        'EURt'
      ],
      [
        'FET',
        'FET'
      ],
      [
        'HIX',
        'HI'
      ],
      [
        'IOT',
        'IOTA'
      ],
      [
        'LBT',
        'LBTC'
      ],
      [
        'LES',
        'LEO-EOS'
      ],
      [
        'LET',
        'LEO-ERC20'
      ],
      [
        'LIFIII',
        'LIF3'
      ],
      [
        'LNX',
        'LN-BTC'
      ],
      [
        'MNA',
        'MANA'
      ],
      [
        'MXNT',
        'MXNt'
      ],
      [
        'OMN',
        'OMNI'
      ],
      [
        'OPX',
        'OP'
      ],
      [
        'PEPEF0',
        'PEPE'
      ],
      [
        'POLF0',
        'POL'
      ],
      [
        'QTM',
        'QTUM'
      ],
      [
        'SCROLL',
        'SCR'
      ],
      [
        'SUIF0',
        'SUI'
      ],
      [
        'TESTADA',
        'ADA'
      ],
      [
        'TESTADAF0',
        'ADA'
      ],
      [
        'TESTALGO',
        'ALGO'
      ],
      [
        'TESTALGOF0',
        'ALGO'
      ],
      [
        'TESTAPT',
        'APT'
      ],
      [
        'TESTAPTF0',
        'APT'
      ],
      [
        'TESTAVAX',
        'AVAX'
      ],
      [
        'TESTAVAXF0',
        'AVAX'
      ],
      [
        'TESTBTC',
        'BTC'
      ],
      [
        'TESTBTCF0',
        'BTC'
      ],
      [
        'TESTDOGE',
        'DOGE'
      ],
      [
        'TESTDOGEF0',
        'DOGE'
      ],
      [
        'TESTDOT',
        'DOT'
      ],
      [
        'TESTDOTF0',
        'DOT'
      ],
      [
        'TESTEOS',
        'EOS'
      ],
      [
        'TESTEOSF0',
        'EOS'
      ],
      [
        'TESTETH',
        'ETH'
      ],
      [
        'TESTETHF0',
        'ETH'
      ],
      [
        'TESTFIL',
        'FIL'
      ],
      [
        'TESTFILF0',
        'FIL'
      ],
      [
        'TESTLTC',
        'LTC'
      ],
      [
        'TESTLTCF0',
        'LTC'
      ],
      [
        'TESTMATIC',
        'MATIC'
      ],
      [
        'TESTNEAR',
        'NEAR'
      ],
      [
        'TESTNEARF0',
        'NEAR'
      ],
      [
        'TESTSOL',
        'SOL'
      ],
      [
        'TESTSOLF0',
        'SOL'
      ],
      [
        'TESTUSD',
        'USD'
      ],
      [
        'TESTUSDT',
        'USDt'
      ],
      [
        'TESTUSDTF0',
        'USDt'
      ],
      [
        'TESTXAUT',
        'XAUT'
      ],
      [
        'TESTXAUTF0',
        'XAUT'
      ],
      [
        'TESTXTZ',
        'XTZ'
      ],
      [
        'TESTXTZF0',
        'XTZ'
      ],
      [
        'TONF0',
        'TON'
      ],
      [
        'TSD',
        'TUSD'
      ],
      [
        'UDC',
        'USDC'
      ],
      [
        'USDTPLY',
        'USDt'
      ],
      [
        'USDTTON',
        'USDt'
      ],
      [
        'USE',
        'USDt'
      ],
      [
        'USS',
        'USDt'
      ],
      [
        'UST',
        'USDt'
      ],
      [
        'USTF0',
        'USDt'
      ],
      [
        'USX',
        'USDt'
      ],
      [
        'WBT',
        'WBTC'
      ],
      [
        'WHBT',
        'WBT'
      ],
      [
        'WXX',
        'W'
      ],
      [
        'XAUT',
        'XAUt'
      ],
      [
        'ZKX',
        'ZK'
      ]
    ],
    [
      [
        '1INCH',
        '1INCH'
      ],
      [
        'AAVE',
        'AAVE'
      ],
      [
        'ADA',
        'Cardano ADA'
      ],
      [
        'AIOZ',
        'AIOZ Network'
      ],
      [
        'ALG',
        'Algorand'
      ],
      [
        'ALT11M2507',
        'ALT11M2507'
      ],
      [
        'ALT11M250830',
        'Nymtech'
      ],
      [
        'ALT11M251029',
        'ALT11M251029'
      ],
      [
        'ALT2612',
        'ALT2612'
      ],
      [
        'AMP',
        'Ampleforth'
      ],
      [
        'APE',
        'ApeCoin'
      ],
      [
        'APENFT',
        'APENFT'
      ],
      [
        'APT',
        'Aptos'
      ],
      [
        'ARB',
        'Arbitrum'
      ],
      [
        'ARBETH',
        'Ethereum (Arbitrum One)'
      ],
      [
        'ATH',
        'Aethir'
      ],
      [
        'ATO',
        'Cosmos-Atom'
      ],
      [
        'AUSDT',
        'aUSDT'
      ],
      [
        'AVAX',
        'Avalanche'
      ],
      [
        'AXS',
        'Axie Infinity'
      ],
      [
        'AZERO',
        'Aleph Zero'
      ],
      [
        'B2M',
        'Bit2Me'
      ],
      [
        'BAL',
        'Balancer'
      ],
      [
        'BCH',
        'Bitcoin Cash'
      ],
      [
        'BCHN',
        'Bitcoin Cash'
      ],
      [
        'BEST',
        'Bitpanda'
      ],
      [
        'BFX',
        'BFX Token'
      ],
      [
        'BGB',
        'Bitget Token'
      ],
      [
        'BLAST',
        'Blast'
      ],
      [
        'BLASTETH',
        'Ethereum (Blast)'
      ],
      [
        'BLUR',
        'BLUR'
      ],
      [
        'BMN',
        'Blockstream Mining Note'
      ],
      [
        'BONK',
        'BONK'
      ],
      [
        'BORG',
        'BORG'
      ],
      [
        'BOSON',
        'Boson Token'
      ],
      [
        'BTC',
        'Bitcoin'
      ],
      [
        'BTT',
        'BitTorrent'
      ],
      [
        'BXN',
        'Blackfort Exchange Network'
      ],
      [
        'CCD',
        'Concordium'
      ],
      [
        'CELO',
        'Celo'
      ],
      [
        'CHEX',
        'CHEX'
      ],
      [
        'CHF',
        'Swiss Franc'
      ],
      [
        'CHZ',
        'socios.com Chiliz'
      ],
      [
        'CNH',
        'Chinese Yuan'
      ],
      [
        'CNHT',
        'Tether CNHt'
      ],
      [
        'COMP',
        'Compound'
      ],
      [
        'COQ',
        'Coq Inu'
      ],
      [
        'CRV',
        'Curve'
      ],
      [
        'DAI',
        'Dai Stablecoin'
      ],
      [
        'DOGE',
        'DOGE'
      ],
      [
        'DOP',
        'Data Ownership Protocol'
      ],
      [
        'DOT',
        'Polkadot'
      ],
      [
        'DSH',
        'Dash'
      ],
      [
        'DYM',
        'Dymension'
      ],
      [
        'EGLD',
        'Elrond'
      ],
      [
        'EIGEN',
        'EigenLayer'
      ],
      [
        'ENA',
        'Ethena Labs'
      ],
      [
        'ENYM',
        'Nymtech (Ethereum)'
      ],
      [
        'EOS',
        'EOS'
      ],
      [
        'ETC',
        'Ethereum Classic'
      ],
      [
        'ETH',
        'Ethereum'
      ],
      [
        'ETHS',
        'ETHS'
      ],
      [
        'ETHW',
        'ETHW'
      ],
      [
        'EUE',
        'EURt (ETH)'
      ],
      [
        'EUR',
        'Euro'
      ],
      [
        'EURQ',
        'Quantoz EURQ'
      ],
      [
        'EURR',
        'EURR'
      ],
      [
        'EUT',
        'Tether EURt'
      ],
      [
        'EXRD',
        'E-RADIX'
      ],
      [
        'FET',
        'Artificial Super Intelligence'
      ],
      [
        'FIL',
        'Filecoin'
      ],
      [
        'FLOKI',
        'FLOKI'
      ],
      [
        'FLR',
        'Flare'
      ],
      [
        'FORTH',
        'FORTH'
      ],
      [
        'FTM',
        'Fantom'
      ],
      [
        'GALA',
        'Gala'
      ],
      [
        'GBP',
        'Pound Sterling'
      ],
      [
        'GMMT',
        'Giant Mammoth'
      ],
      [
        'GNO',
        'Gnosis'
      ],
      [
        'GOMINING',
        'GoMining'
      ],
      [
        'GRT',
        'The Graph'
      ],
      [
        'GTX',
        'Gate.IO'
      ],
      [
        'HIX',
        'Hi Dollar'
      ],
      [
        'HKD',
        'Hong Kong Dollar'
      ],
      [
        'HMSTR',
        'Hamster Kombat'
      ],
      [
        'HTXDAO',
        'HTXDAO'
      ],
      [
        'ICP',
        'Dfinity'
      ],
      [
        'INJ',
        'Injective'
      ],
      [
        'IOT',
        'Iota'
      ],
      [
        'JASMY',
        'Jasmy'
      ],
      [
        'JPY',
        'Japanese Yen'
      ],
      [
        'JST',
        'JST'
      ],
      [
        'JUP',
        'Jupiter'
      ],
      [
        'JUSTICE',
        'AssangeDAO'
      ],
      [
        'JXX',
        'Jambo'
      ],
      [
        'KAN',
        'BitKan'
      ],
      [
        'KARATE',
        'KARATE'
      ],
      [
        'KAVA',
        'KAVA'
      ],
      [
        'KMNO',
        'Kamino Finance'
      ],
      [
        'LBT',
        'Bitcoin (Liquid)'
      ],
      [
        'LDO',
        'Lido'
      ],
      [
        'LEO',
        'Unus Sed LEO'
      ],
      [
        'LES',
        'Unus Sed LEO (EOS)'
      ],
      [
        'LET',
        'Unus Sed LEO (ERC20)'
      ],
      [
        'LIFIII',
        'LIF3'
      ],
      [
        'LINK',
        'ChainLink'
      ],
      [
        'LNX',
        'Bitcoin (Lightning Network)'
      ],
      [
        'LTC',
        'Litecoin'
      ],
      [
        'LUNA2',
        'LUNA2'
      ],
      [
        'LYM',
        'Lympo'
      ],
      [
        'MANEKI',
        'MANEKI'
      ],
      [
        'MATIC',
        'MATIC (Ethereum)'
      ],
      [
        'MEW',
        'cat in a dogs world'
      ],
      [
        'MIM',
        'Magic Internet Money'
      ],
      [
        'MKR',
        'Maker'
      ],
      [
        'MLN',
        'Melon'
      ],
      [
        'MNA',
        'Decentraland'
      ],
      [
        'MODE',
        'Mode Network'
      ],
      [
        'MODEETH',
        'Ethereum (Mode Network)'
      ],
      [
        'MPC',
        'Partisia Blockchain'
      ],
      [
        'MXNT',
        'Tether MXNt'
      ],
      [
        'MXNTE',
        'MXNt (ETH)'
      ],
      [
        'NEAR',
        'Near'
      ],
      [
        'NEO',
        'NEO'
      ],
      [
        'NEOGAS',
        'NEOGAS'
      ],
      [
        'NEXO',
        'NEXO'
      ],
      [
        'NOT',
        'Notcoin'
      ],
      [
        'NYM',
        'Nymtech'
      ],
      [
        'OMG',
        'OmiseGO'
      ],
      [
        'OMN',
        'Omni'
      ],
      [
        'OPX',
        'Optimism'
      ],
      [
        'OPXETH',
        'Ethereum (Optimism)'
      ],
      [
        'PAX',
        'Paxos'
      ],
      [
        'PEPE',
        'PEPE'
      ],
      [
        'PLU',
        'Pluton'
      ],
      [
        'PNK',
        'Kleros'
      ],
      [
        'POL',
        'Polygon Ecosystem Token (Ethereum)'
      ],
      [
        'POLM',
        'Polygon Ecosystem Token (Polygon)'
      ],
      [
        'PORTAL',
        'Portal'
      ],
      [
        'QTM',
        'Qtum'
      ],
      [
        'RLY',
        'Rally'
      ],
      [
        'RRT',
        'Recovery Right Tokens'
      ],
      [
        'SAND',
        'SAND'
      ],
      [
        'SCROLL',
        'Scroll'
      ],
      [
        'SCROLLETH',
        'Ethereum (Scroll)'
      ],
      [
        'SEI',
        'Sei Network'
      ],
      [
        'SHIB',
        'SHIB'
      ],
      [
        'SNX',
        'Synthetix Network'
      ],
      [
        'SOL',
        'Solana'
      ],
      [
        'SPEC',
        'Spectral'
      ],
      [
        'SPELL',
        'SPELL'
      ],
      [
        'STG',
        'Stargate Finance'
      ],
      [
        'STRK',
        'Starknet'
      ],
      [
        'SUI',
        'SUI'
      ],
      [
        'SUKU',
        'SUKU'
      ],
      [
        'SUN',
        'SUN'
      ],
      [
        'SUSHI',
        'SUSHI'
      ],
      [
        'SWEAT',
        'SWEAT'
      ],
      [
        'SWEATNEP',
        'SWEAT (NEP-141)'
      ],
      [
        'TAIKO',
        'Taiko'
      ],
      [
        'TAIKOETH',
        'Ethereum (Taiko)'
      ],
      [
        'TESTBTC',
        'Bitcoin'
      ],
      [
        'TESTDOT',
        'Polkadot'
      ],
      [
        'TESTMATIC',
        'MATIC (Ethereum)'
      ],
      [
        'TESTSOL',
        'Solana'
      ],
      [
        'TESTUSD',
        'US Dollar'
      ],
      [
        'TESTUSDT',
        'Tether USDt'
      ],
      [
        'TESTUSDTF0',
        'Tether USDt'
      ],
      [
        'TIA',
        'Celestia'
      ],
      [
        'TITAN1',
        'TITAN1'
      ],
      [
        'TITAN2',
        'TITAN2'
      ],
      [
        'TLOS',
        'TELOS'
      ],
      [
        'TOKEN',
        'TokenFi'
      ],
      [
        'TOMI',
        'tomiNET'
      ],
      [
        'TON',
        'Toncoin'
      ],
      [
        'TRADE',
        'Polytrade'
      ],
      [
        'TRX',
        'TRON'
      ],
      [
        'TRY',
        'Turkish Lira'
      ],
      [
        'TSD',
        'TrueUSD'
      ],
      [
        'TURBO',
        'Turbo'
      ],
      [
        'UDC',
        'USDc'
      ],
      [
        'UNI',
        'Uniswap'
      ],
      [
        'UOS',
        'Ultra'
      ],
      [
        'USD',
        'US Dollar'
      ],
      [
        'USDQ',
        'Quantoz USDQ'
      ],
      [
        'USDR',
        'USDR'
      ],
      [
        'USDTALG',
        'USDt (Algorand)'
      ],
      [
        'USDTAVAX',
        'USDt (AVAX-C)'
      ],
      [
        'USDTBCH',
        'USDt (BCH)'
      ],
      [
        'USDTCELO',
        'USDt (Celo)'
      ],
      [
        'USDTDOT',
        'USDt (Polkadot)'
      ],
      [
        'USDTKAVA',
        'USDt (Kava)'
      ],
      [
        'USDTKSM',
        'USDTKSM'
      ],
      [
        'USDTNEAR',
        'USDt (Near)'
      ],
      [
        'USDTPLY',
        'USDt (Polygon)'
      ],
      [
        'USDTSOL',
        'USDt (SOL)'
      ],
      [
        'USDTTON',
        'USDt (Ton)'
      ],
      [
        'USDTXTZ',
        'USDt (Tezos)'
      ],
      [
        'USDTZK',
        'USDt (zkEVM)'
      ],
      [
        'USE',
        'USDt (ETH)'
      ],
      [
        'USO',
        'USDt (Omni)'
      ],
      [
        'USS',
        'USDt (EOS)'
      ],
      [
        'UST',
        'Tether USDt'
      ],
      [
        'USTBL',
        'USTBL'
      ],
      [
        'USX',
        'USDt (Tron)'
      ],
      [
        'UXLINK',
        'UXLINK'
      ],
      [
        'VELAR',
        'Velar'
      ],
      [
        'VET',
        'VeChain'
      ],
      [
        'WAVES',
        'WAVES'
      ],
      [
        'WBT',
        'Wrapped Bitcoin'
      ],
      [
        'WHBT',
        'WhiteBIT Token'
      ],
      [
        'WIF',
        'Dogwifhat'
      ],
      [
        'WILD',
        'Wilder World'
      ],
      [
        'WNCG',
        'WNCG'
      ],
      [
        'WOO',
        'WOO'
      ],
      [
        'WXX',
        'Wormhole'
      ],
      [
        'XAUT',
        'Tether XAUt'
      ],
      [
        'XAUTE',
        'XAUTe'
      ],
      [
        'XAUTZK',
        'XAUt (zkEVM)'
      ],
      [
        'XDC',
        'XinFin'
      ],
      [
        'XLM',
        'Stellar Lumen'
      ],
      [
        'XMR',
        'Monero'
      ],
      [
        'XRD',
        'RADIX'
      ],
      [
        'XRP',
        'Ripple'
      ],
      [
        'XTP',
        'Tap'
      ],
      [
        'XTZ',
        'Tezos'
      ],
      [
        'XVG',
        'Verge'
      ],
      [
        'YFI',
        'Yearn.Finance'
      ],
      [
        'ZEC',
        'Zcash'
      ],
      [
        'ZETA',
        'ZetaChain'
      ],
      [
        'ZKX',
        'zkSync'
      ],
      [
        'ZKXETH',
        'Ethereum (zkSync Era)'
      ],
      [
        'ZRO',
        'LayerZero'
      ],
      [
        'ZRX',
        '0x'
      ]
    ],
    [
      [
        '1INCH',
        'ETH'
      ],
      [
        'AAVE',
        'ETH'
      ],
      [
        'AIOZ',
        'ETH'
      ],
      [
        'AMP',
        'ETH'
      ],
      [
        'APE',
        'ETH'
      ],
      [
        'APENFT',
        'TRX'
      ],
      [
        'ARB',
        'ARBETH'
      ],
      [
        'ATH',
        'ETH'
      ],
      [
        'AUSDT',
        'ETH'
      ],
      [
        'AXS',
        'ETH'
      ],
      [
        'B2M',
        'ETH'
      ],
      [
        'BAL',
        'ETH'
      ],
      [
        'BEST',
        'ETH'
      ],
      [
        'BGB',
        'ETH'
      ],
      [
        'BLAST',
        'BLASTETH'
      ],
      [
        'BLUR',
        'ETH'
      ],
      [
        'BONK',
        'SOL'
      ],
      [
        'BORG',
        'ETH'
      ],
      [
        'BOSON',
        'ETH'
      ],
      [
        'BTT',
        'TRX'
      ],
      [
        'CHEX',
        'EOS'
      ],
      [
        'CHZ',
        'ETH'
      ],
      [
        'CNHTE',
        'ETH'
      ],
      [
        'CNHTX',
        'TRX'
      ],
      [
        'COMP',
        'ETH'
      ],
      [
        'COQ',
        'AVAXC'
      ],
      [
        'CRV',
        'ETH'
      ],
      [
        'DAI',
        'ETH'
      ],
      [
        'DOP',
        'ETH'
      ],
      [
        'EIGEN',
        'ETH'
      ],
      [
        'ENA',
        'ETH'
      ],
      [
        'ENYM',
        'ETH'
      ],
      [
        'EUE',
        'ETH'
      ],
      [
        'EURQ',
        'ETH'
      ],
      [
        'EURR',
        'ETH'
      ],
      [
        'EXRD',
        'ETH'
      ],
      [
        'FET',
        'ETH'
      ],
      [
        'FLOKI',
        'ETH'
      ],
      [
        'FORTH',
        'ETH'
      ],
      [
        'GALA',
        'ETH'
      ],
      [
        'GNO',
        'ETH'
      ],
      [
        'GOMINING',
        'ETH'
      ],
      [
        'GRT',
        'ETH'
      ],
      [
        'GTX',
        'ETH'
      ],
      [
        'HIX',
        'ETH'
      ],
      [
        'HMSTR',
        'TON'
      ],
      [
        'HTXDAO',
        'TRX'
      ],
      [
        'JASMY',
        'ETH'
      ],
      [
        'JST',
        'TRX'
      ],
      [
        'JUP',
        'SOL'
      ],
      [
        'JUSTICE',
        'ETH'
      ],
      [
        'JXX',
        'SOL'
      ],
      [
        'KAN',
        'ETH'
      ],
      [
        'KARATE',
        'ETH'
      ],
      [
        'KMNO',
        'SOL'
      ],
      [
        'LDO',
        'ETH'
      ],
      [
        'LES',
        'EOS'
      ],
      [
        'LET',
        'ETH'
      ],
      [
        'LIFIII',
        'ETH'
      ],
      [
        'LINK',
        'ETH'
      ],
      [
        'LYM',
        'ETH'
      ],
      [
        'MANEKI',
        'SOL'
      ],
      [
        'MATIC',
        'ETH'
      ],
      [
        'MEW',
        'SOL'
      ],
      [
        'MIM',
        'ETH'
      ],
      [
        'MKR',
        'ETH'
      ],
      [
        'MLN',
        'ETH'
      ],
      [
        'MNA',
        'ETH'
      ],
      [
        'MODE',
        'MODEETH'
      ],
      [
        'MXNTE',
        'ETH'
      ],
      [
        'NEXO',
        'ETH'
      ],
      [
        'NOT',
        'TON'
      ],
      [
        'OMG',
        'ETH'
      ],
      [
        'OPX',
        'OPXETH'
      ],
      [
        'PAX',
        'ETH'
      ],
      [
        'PEPE',
        'ETH'
      ],
      [
        'PLU',
        'ETH'
      ],
      [
        'PNK',
        'ETH'
      ],
      [
        'POL',
        'ETH'
      ],
      [
        'PORTAL',
        'ETH'
      ],
      [
        'RLY',
        'ETH'
      ],
      [
        'SAND',
        'ETH'
      ],
      [
        'SCROLL',
        'SCROLLETH'
      ],
      [
        'SHIB',
        'ETH'
      ],
      [
        'SNX',
        'ETH'
      ],
      [
        'SPEC',
        'ETH'
      ],
      [
        'SPELL',
        'ETH'
      ],
      [
        'STG',
        'ETH'
      ],
      [
        'STRK',
        'ETH'
      ],
      [
        'SUKU',
        'ETH'
      ],
      [
        'SUN',
        'TRX'
      ],
      [
        'SUSHI',
        'ETH'
      ],
      [
        'SWEAT',
        'ETH'
      ],
      [
        'TAIKO',
        'TAIKOETH'
      ],
      [
        'TOKEN',
        'ETH'
      ],
      [
        'TOMI',
        'ETH'
      ],
      [
        'TRADE',
        'ETH'
      ],
      [
        'TSD',
        'ETH'
      ],
      [
        'TURBO',
        'ETH'
      ],
      [
        'UDC',
        'ETH'
      ],
      [
        'UNI',
        'ETH'
      ],
      [
        'UOS',
        'ETH'
      ],
      [
        'USDQ',
        'ETH'
      ],
      [
        'USDR',
        'ETH'
      ],
      [
        'USDTAVAX',
        'AVAXC'
      ],
      [
        'USDTCELO',
        'CELO'
      ],
      [
        'USDTKAVA',
        'KAVA'
      ],
      [
        'USDTPLY',
        'POLM'
      ],
      [
        'USDTSOL',
        'SOL'
      ],
      [
        'USDTZK',
        'ZKETH'
      ],
      [
        'USE',
        'ETH'
      ],
      [
        'USL',
        'LBT'
      ],
      [
        'USS',
        'EOS'
      ],
      [
        'USX',
        'TRX'
      ],
      [
        'UXLINK',
        'ARBETH'
      ],
      [
        'VELAR',
        'ETH'
      ],
      [
        'WBT',
        'ETH'
      ],
      [
        'WHBT',
        'ETH'
      ],
      [
        'WIF',
        'SOL'
      ],
      [
        'WILD',
        'ETH'
      ],
      [
        'WNCG',
        'ETH'
      ],
      [
        'WOO',
        'ETH'
      ],
      [
        'WXX',
        'SOL'
      ],
      [
        'XAUTE',
        'ETH'
      ],
      [
        'XAUTZK',
        'ZKETH'
      ],
      [
        'XTP',
        'ETH'
      ],
      [
        'YFI',
        'ETH'
      ],
      [
        'ZETA',
        'ETH'
      ],
      [
        'ZKX',
        'ZKXETH'
      ],
      [
        'ZRO',
        'ETH'
      ],
      [
        'ZRX',
        'ETH'
      ]
    ],
    [
      [
        'ADA',
        [
          'https://adastat.net',
          'https://adastat.net/addresses/VAL',
          'https://adastat.net/transactions/VAL'
        ]
      ],
      [
        'ALG',
        [
          'https://allo.info',
          'https://allo.info/account/VAL ',
          'https://allo.info/tx/VAL'
        ]
      ],
      [
        'APT',
        [
          'https://explorer.aptoslabs.com',
          'https://explorer.aptoslabs.com/account/VAL',
          'https://explorer.aptoslabs.com/txn/VAL'
        ]
      ],
      [
        'ARBETH',
        [
          'https://arbiscan.io',
          'https://arbiscan.io/address/VAL',
          'https://arbiscan.io/tx/VAL'
        ]
      ],
      [
        'ATO',
        [
          'https://www.mintscan.io/cosmos',
          'https://www.mintscan.io/cosmos/account/VAL',
          'https://www.mintscan.io/cosmos/txs/VAL'
        ]
      ],
      [
        'AVAX',
        [
          'https://avascan.info',
          'https://avascan.info/blockchain/x/address/VAL',
          'https://avascan.info/blockchain/x/tx/VAL'
        ]
      ],
      [
        'AVAXC',
        [
          'https://avascan.info',
          'https://avascan.info/blockchain/c/address/VAL',
          'https://avascan.info/blockchain/c/tx/VAL'
        ]
      ],
      [
        'AZERO',
        [
          'https://alephzero.subscan.io',
          'https://alephzero.subscan.io/account/VAL',
          'https://alephzero.subscan.io/extrinsic/VAL'
        ]
      ],
      [
        'BCHN',
        [
          'https://blockchair.com/bitcoin-cash',
          'https://blockchair.com/bitcoin-cash/address/VAL',
          'https://blockchair.com/bitcoin-cash/transaction/VAL'
        ]
      ],
      [
        'BTC',
        [
          'https://blockstream.info',
          'https://blockstream.info/address/VAL',
          'https://blockstream.info/tx/VAL'
        ]
      ],
      [
        'BXN',
        [
          'https://explorer.blackfort.network',
          'https://explorer.blackfort.network/address/VAL',
          'https://explorer.blackfort.network/tx/VAL'
        ]
      ],
      [
        'CCD',
        [
          'https://dashboard.mainnet.concordium.software',
          'https://dashboard.mainnet.concordium.software/address/VAL',
          'https://dashboard.mainnet.concordium.software/lookup/VAL'
        ]
      ],
      [
        'CELO',
        [
          'https://celoscan.io',
          'https://celoscan.io/address/VAL',
          'https://celoscan.io/tx/VAL'
        ]
      ],
      [
        'DOGE',
        [
          'https://dogechain.info',
          'https://dogechain.info/address/VAL',
          'https://dogechain.info/tx/VAL'
        ]
      ],
      [
        'DOT',
        [
          'https://polkadot.subscan.io',
          'https://polkadot.subscan.io/account/VAL',
          'https://polkadot.subscan.io/extrinsic/VAL'
        ]
      ],
      [
        'DSH',
        [
          'https://chainz.cryptoid.info/dash',
          'https://chainz.cryptoid.info/dash/address.dws?VAL',
          'https://chainz.cryptoid.info/dash/tx.dws?VAL'
        ]
      ],
      [
        'DYM',
        [
          'https://dym.fyi',
          'https://dym.fyi/address/VAL',
          'https://dym.fyi/tx/VAL'
        ]
      ],
      [
        'EGLD',
        [
          'https://explorer.multiversx.com',
          'https://explorer.multiversx.com/address/VAL',
          'https://explorer.multiversx.com/transactions/VAL'
        ]
      ],
      [
        'EOS',
        [
          'https://eosflare.io',
          'https://eosflare.io/account/VAL',
          'https://eosflare.io/tx/VAL'
        ]
      ],
      [
        'ETC',
        [
          'https://blockscout.com/etc/mainnet',
          'https://blockscout.com/etc/mainnet/address/VAL',
          'https://blockscout.com/etc/mainnet/tx/VAL'
        ]
      ],
      [
        'ETH',
        [
          'https://etherscan.io',
          'https://etherscan.io/address/VAL',
          'https://etherscan.io/tx/VAL'
        ]
      ],
      [
        'ETHW',
        [
          'https://www.oklink.com/ethw',
          'https://www.oklink.com/ethw/address/VAL',
          'https://www.oklink.com/ethw/tx/VAL'
        ]
      ],
      [
        'FIL',
        [
          'https://filfox.info/en',
          'https://filfox.info/en/address/VAL',
          'https://filfox.info/en/message/VAL'
        ]
      ],
      [
        'FLR',
        [
          'https://flare-explorer.flare.network',
          'https://flare-explorer.flare.network/address/VAL',
          'https://flare-explorer.flare.network/tx/VAL'
        ]
      ],
      [
        'FTM',
        [
          'https://ftmscan.com',
          'https://ftmscan.com/address/VAL',
          'https://ftmscan.com/tx/VAL'
        ]
      ],
      [
        'GMMT',
        [
          'https://scan.gmmtchain.io',
          'https://scan.gmmtchain.io/address/VAL',
          'https://scan.gmmtchain.io/tx/VAL'
        ]
      ],
      [
        'ICP',
        [
          'https://dashboard.internetcomputer.org',
          'https://dashboard.internetcomputer.org/account/VAL',
          'https://dashboard.internetcomputer.org/transaction/VAL'
        ]
      ],
      [
        'INJ',
        [
          'https://www.mintscan.io/injective',
          'https://www.mintscan.io/injective/address/VAL',
          'https://www.mintscan.io/injective/tx/VAL'
        ]
      ],
      [
        'IOT',
        [
          'https://explorer.iota.org/mainnet',
          'https://explorer.iota.org/mainnet/addr/VAL',
          'https://explorer.iota.org/mainnet/transaction/VAL'
        ]
      ],
      [
        'KAVA',
        [
          'https://www.mintscan.io/kava',
          'https://www.mintscan.io/kava/account/VAL',
          'https://www.mintscan.io/kava/txs/VAL'
        ]
      ],
      [
        'LBT',
        [
          'https://blockstream.info/liquid',
          'https://blockstream.info/liquid/address/VAL',
          'https://blockstream.info/liquid/tx/VAL'
        ]
      ],
      [
        'LTC',
        [
          'https://blockchair.com/litecoin',
          'https://blockchair.com/litecoin/address/VAL',
          'https://blockchair.com/litecoin/transaction/VAL'
        ]
      ],
      [
        'LUNA2',
        [
          'https://finder.terra.money',
          'https://finder.terra.money/mainnet/address/VAL',
          'https://finder.terra.money/mainnet/tx/VAL'
        ]
      ],
      [
        'MPC',
        [
          'https://browser.partisiablockchain.com',
          'https://browser.partisiablockchain.com/accounts/VAL',
          'https://browser.partisiablockchain.com/transactions/VAL'
        ]
      ],
      [
        'NEAR',
        [
          'https://nearblocks.io',
          'https://nearblocks.io/address/VAL',
          'https://nearblocks.io/txns/VAL'
        ]
      ],
      [
        'NEO',
        [
          'https://dora.coz.io',
          'https://dora.coz.io/address/neo3/mainnet/VAL/assets',
          'https://dora.coz.io/transaction/neo3/mainnet/VAL'
        ]
      ],
      [
        'NYM',
        [
          'https://nym.explorers.guru',
          'https://nym.explorers.guru/account/VAL',
          'https://nym.explorers.guru/transaction/VAL'
        ]
      ],
      [
        'OMN',
        [
          'http://omniexplorer.info',
          'http://omniexplorer.info/lookupadd.aspx?address=VAL',
          'http://omniexplorer.info/lookuptx.aspx?txid=VAL'
        ]
      ],
      [
        'OPXETH',
        [
          'https://optimistic.etherscan.io',
          'https://optimistic.etherscan.io/address/VAL',
          'https://optimistic.etherscan.io/tx/VAL'
        ]
      ],
      [
        'POLM',
        [
          'https://polygonscan.com',
          'https://polygonscan.com/address/VAL',
          'https://polygonscan.com/tx/VAL'
        ]
      ],
      [
        'QTM',
        [
          'https://qtum.info',
          'https://qtum.info/address/VAL',
          'https://qtum.info/tx/VAL'
        ]
      ],
      [
        'SEI',
        [
          'https://www.seiscan.app/pacific-1',
          'https://www.seiscan.app/pacific-1/accounts/VAL',
          'https://www.seiscan.app/pacific-1/txs/VAL'
        ]
      ],
      [
        'SOL',
        [
          'https://solscan.io',
          'https://solscan.io/account/VAL',
          'https://solscan.io/tx/VAL'
        ]
      ],
      [
        'SUI',
        [
          'https://www.oklink.com/sui',
          'https://www.oklink.com/sui/address/VAL',
          'https://www.oklink.com/sui/tx/VAL'
        ]
      ],
      [
        'SWEATNEP',
        [
          'https://nearblocks.io',
          'https://nearblocks.io/address/VAL',
          'https://nearblocks.io/txns/VAL'
        ]
      ],
      [
        'TIA',
        [
          'https://www.mintscan.io/celestia',
          'https://www.mintscan.io/celestia/address/VAL',
          'https://www.mintscan.io/celestia/tx/VAL'
        ]
      ],
      [
        'TLOS',
        [
          'https://explorer.telos.net',
          'https://explorer.telos.net/account/VAL',
          'https://explorer.telos.net/transaction/VAL'
        ]
      ],
      [
        'TON',
        [
          'https://tonviewer.com',
          'https://tonviewer.com/VAL',
          'https://tonviewer.com/transaction/VAL'
        ]
      ],
      [
        'TRX',
        [
          'https://tronscan.org/#',
          'https://tronscan.org/#/address/VAL',
          'https://tronscan.org/#/transaction/VAL'
        ]
      ],
      [
        'USDTALG',
        [
          'https://allo.info',
          'https://allo.info/account/VAL ',
          'https://allo.info/tx/VAL'
        ]
      ],
      [
        'USDTAPT',
        [
          'https://explorer.aptoslabs.com',
          'https://explorer.aptoslabs.com/account/VAL',
          'https://explorer.aptoslabs.com/txn/VAL'
        ]
      ],
      [
        'USDTBCH',
        [
          'https://simpleledger.info',
          'https://simpleledger.info/address/VAL',
          'https://simpleledger.info/tx/VAL'
        ]
      ],
      [
        'USDTDOT',
        [
          'https://statemint.subscan.io',
          'https://statemint.subscan.io/account/VAL',
          'https://statemint.subscan.io/extrinsic/VAL'
        ]
      ],
      [
        'USDTKSM',
        [
          'https://statemine.subscan.io',
          'https://statemine.subscan.io/account/VAL',
          'https://statemine.subscan.io/extrinsic/VAL'
        ]
      ],
      [
        'USDTNEAR',
        [
          'https://nearblocks.io',
          'https://nearblocks.io/address/VAL',
          'https://nearblocks.io/txns/VAL'
        ]
      ],
      [
        'USDTTON',
        [
          'https://tonviewer.com',
          'https://tonviewer.com/VAL',
          'https://tonviewer.com/transaction/VAL'
        ]
      ],
      [
        'USDTXTZ',
        [
          'https://tzkt.io',
          'https://tzkt.io/VAL',
          'https://tzkt.io/VAL'
        ]
      ],
      [
        'USO',
        [
          'https://www.omniexplorer.info',
          'https://www.omniexplorer.info/lookupadd.aspx?address=VAL',
          'https://www.omniexplorer.info/lookuptx.aspx?txid=VAL'
        ]
      ],
      [
        'VET',
        [
          'https://explore.vechain.org',
          'https://explore.vechain.org/accounts/VAL',
          'https://explore.vechain.org/transactions/VAL'
        ]
      ],
      [
        'WAVES',
        [
          'https://wavesexplorer.com',
          'https://wavesexplorer.com/address/VAL',
          'https://wavesexplorer.com/tx/VAL'
        ]
      ],
      [
        'XDC',
        [
          'https://xdcscan.com',
          'https://xdcscan.com/address/VAL',
          'https://xdcscan.com/tx/VAL'
        ]
      ],
      [
        'XLM',
        [
          'https://stellarchain.io',
          'https://stellarchain.io/address/VAL',
          'https://stellarchain.io/tx/VAL'
        ]
      ],
      [
        'XMR',
        [
          'https://moneroblocks.info',
          'https://moneroblocks.info/search/VAL',
          'https://moneroblocks.info/search/VAL'
        ]
      ],
      [
        'XRD',
        [
          'https://dashboard.radixdlt.com',
          'https://dashboard.radixdlt.com/account/VAL',
          'https://dashboard.radixdlt.com/transaction/VAL'
        ]
      ],
      [
        'XRP',
        [
          'https://xrpscan.com',
          'https://xrpscan.com/account/VAL',
          'https://xrpscan.com/tx/VAL'
        ]
      ],
      [
        'XTZ',
        [
          'https://tzkt.io',
          'https://tzkt.io/VAL',
          'https://tzkt.io/VAL'
        ]
      ],
      [
        'XVG',
        [
          'https://verge-blockchain.info',
          'https://verge-blockchain.info/address/VAL',
          'https://verge-blockchain.info/tx/VAL'
        ]
      ],
      [
        'ZEC',
        [
          'https://blockexplorer.one/zcash/mainnet',
          'https://blockexplorer.one/zcash/mainnet/address/VAL',
          'https://blockexplorer.one/zcash/mainnet/tx/VAL'
        ]
      ]
    ],
    [
      [
        'LBT',
        [
          [
            'BTC',
            1
          ]
        ]
      ],
      [
        'BTC',
        [
          [
            'LBT',
            1
          ],
          [
            'LNX',
            1
          ],
          [
            'BTCF0',
            1
          ]
        ]
      ],
      [
        'BTCF0',
        [
          [
            'BTC',
            1
          ]
        ]
      ],
      [
        'LEO',
        [
          [
            'LET',
            1
          ],
          [
            'LES',
            1
          ]
        ]
      ],
      [
        'LES',
        [
          [
            'LEO',
            1
          ]
        ]
      ],
      [
        'LET',
        [
          [
            'LEO',
            1
          ]
        ]
      ],
      [
        'UST',
        [
          [
            'USTF0',
            1
          ]
        ]
      ],
      [
        'USTF0',
        [
          [
            'UST',
            1
          ]
        ]
      ],
      [
        'LNX',
        [
          [
            'BTC',
            1
          ]
        ]
      ],
      [
        'TESTUSDT',
        [
          [
            'TESTUSDTF0',
            1
          ]
        ]
      ],
      [
        'TESTUSDTF0',
        [
          [
            'TESTUSDT',
            1
          ]
        ]
      ],
      [
        'ETH',
        [
          [
            'ETH2P',
            1
          ],
          [
            'ARBETH',
            1
          ]
        ]
      ],
      [
        'EUT',
        [
          [
            'EUTF0',
            1
          ]
        ]
      ],
      [
        'EUTF0',
        [
          [
            'EUT',
            1
          ]
        ]
      ],
      [
        'XRD',
        [
          [
            'EXRD',
            1
          ]
        ]
      ],
      [
        'EXRD',
        [
          [
            'XRD',
            1
          ]
        ]
      ],
      [
        'MATIC',
        [
          [
            'POLM',
            1
          ],
          [
            'POL',
            1
          ]
        ]
      ],
      [
        'ETH2X',
        [
          [
            'ETH2U',
            1
          ]
        ]
      ],
      [
        'ETH2R',
        [
          [
            'ETH2U',
            1
          ]
        ]
      ],
      [
        'ARBETH',
        [
          [
            'ETH',
            1
          ]
        ]
      ],
      [
        'SWEAT',
        [
          [
            'SWEATNEP',
            1
          ]
        ]
      ],
      [
        'SWEATNEP',
        [
          [
            'SWEAT',
            1
          ]
        ]
      ],
      [
        'POL',
        [
          [
            'POLM',
            1
          ]
        ]
      ],
      [
        'POLM',
        [
          [
            'POL',
            1
          ]
        ]
      ],
      [
        'ENYM',
        [
          [
            'NYM',
            1
          ]
        ]
      ],
      [
        'NYM',
        [
          [
            'ENYM',
            1
          ]
        ]
      ]
    ]]
  ]
])
