'use strict'

module.exports = {
  MAC_ABOUT_MENU_ITEM: 'MAC_ABOUT_MENU_ITEM',
  MAC_SERVICES_MENU_ITEM: 'MAC_SERVICES_MENU_ITEM',
  MAC_HIDE_MENU_ITEM: 'MAC_HIDE_MENU_ITEM',
  MAC_HIDE_OTHERS_MENU_ITEM: 'MAC_HIDE_OTHERS_MENU_ITEM',
  MAC_UNHIDE_MENU_ITEM: 'MAC_UNHIDE_MENU_ITEM',
  MAC_QUIT_MENU_ITEM: 'MAC_QUIT_MENU_ITEM',
  MAC_CLOSE_MENU_ITEM: 'MAC_CLOSE_MENU_ITEM',
  MAC_PASTE_AND_MATCH_STYLE_MENU_ITEM: 'MAC_PASTE_AND_MATCH_STYLE_MENU_ITEM',
  MAC_START_SPEAKING_MENU_ITEM: 'MAC_START_SPEAKING_MENU_ITEM',
  MAC_STOP_SPEAKING_MENU_ITEM: 'MAC_STOP_SPEAKING_MENU_ITEM',
  MAC_FRONT_MENU_ITEM: 'MAC_FRONT_MENU_ITEM',
  MAC_WINDOW_MENU_ITEM: 'MAC_WINDOW_MENU_ITEM',

  QUIT_MENU_ITEM: 'QUIT_MENU_ITEM',

  UNDO_MENU_ITEM: 'UNDO_MENU_ITEM',
  REDO_MENU_ITEM: 'REDO_MENU_ITEM',
  CUT_MENU_ITEM: 'CUT_MENU_ITEM',
  COPY_MENU_ITEM: 'COPY_MENU_ITEM',
  PASTE_MENU_ITEM: 'PASTE_MENU_ITEM',
  DELETE_MENU_ITEM: 'DELETE_MENU_ITEM',
  SELECT_ALL_MENU_ITEM: 'SELECT_ALL_MENU_ITEM',

  RELOAD_MENU_ITEM: 'RELOAD_MENU_ITEM',
  FORCE_RELOAD_MENU_ITEM: 'FORCE_RELOAD_MENU_ITEM',
  TOGGLE_DEV_TOOLS_MENU_ITEM: 'TOGGLE_DEV_TOOLS_MENU_ITEM',
  RESET_ZOOM_MENU_ITEM: 'RESET_ZOOM_MENU_ITEM',
  ZOOM_IN_MENU_ITEM: 'ZOOM_IN_MENU_ITEM',
  ZOOM_OUT_MENU_ITEM: 'ZOOM_OUT_MENU_ITEM',
  TOGGLE_FULL_SCREEN_MENU_ITEM: 'TOGGLE_FULL_SCREEN_MENU_ITEM',

  MINIMIZE_MENU_ITEM: 'MINIMIZE_MENU_ITEM',
  ZOOM_MENU_ITEM: 'ZOOM_MENU_ITEM',
  CLOSE_MENU_ITEM: 'CLOSE_MENU_ITEM',

  EXPORT_DB_MENU_ITEM: 'EXPORT_DB_MENU_ITEM',
  IMPORT_DB_MENU_ITEM: 'IMPORT_DB_MENU_ITEM',
  RESTORE_DB_MENU_ITEM: 'RESTORE_DB_MENU_ITEM',
  BACKUP_DB_MENU_ITEM: 'BACKUP_DB_MENU_ITEM',
  REMOVE_DB_MENU_ITEM: 'REMOVE_DB_MENU_ITEM',
  CLEAR_ALL_DATA_MENU_ITEM: 'CLEAR_ALL_DATA_MENU_ITEM',
  CHANGE_REPORTS_FOLDER_MENU_ITEM: 'CHANGE_REPORTS_FOLDER_MENU_ITEM',
  CHANGE_SYNC_FREQUENCY_MENU_ITEM: 'CHANGE_SYNC_FREQUENCY_MENU_ITEM',

  REPORT_BUG_MENU_ITEM: 'REPORT_BUG_MENU_ITEM',
  CHECK_UPDATE_MENU_ITEM: 'CHECK_UPDATE_MENU_ITEM',
  INSTALL_UPDATE_MENU_ITEM: 'INSTALL_UPDATE_MENU_ITEM',
  USER_MANUAL_MENU_ITEM: 'USER_MANUAL_MENU_ITEM',
  SHOW_CHANGE_LOG_MENU_ITEM: 'SHOW_CHANGE_LOG_MENU_ITEM',
  ABOUT_MENU_ITEM: 'ABOUT_MENU_ITEM'
}
