name: CI
run-name: 'Run tests: Commit ${{ github.sha }}'

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - master
  workflow_dispatch:

jobs:
  linux-test-runner:
    name: Linux Test Runner
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        submodules: recursive
    - uses: actions/setup-node@v6.3.0
      with:
        node-version: 24.18.0
    - name: Setup configs and install deps
      run: ./scripts/setup.sh -u
    - name: Run tests
      run: npm test -- -- --reporter=json --reporter-option output=test-report.json
    - uses: actions/upload-artifact@v7.0.0
      if: success() || failure()
      with:
        name: test-results
        path: test-report.json
  web-page-report:
    needs: linux-test-runner
    permissions:
      contents: read
      actions: read
      checks: write
    uses: ./.github/workflows/test-report.yml
