name: CI
run-name: 'Run tests: Commit ${{ github.sha }}'

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - master
  workflow_dispatch:

jobs:
  linux-test-runner:
    name: Linux Test Runner
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: 20.18.1
    - name: Setup configs and install deps
      run: ./scripts/setup.sh -u
    - name: Run tests
      uses: nick-fields/retry@v3
      continue-on-error: false
      with:
        timeout_minutes: 20
        retry_wait_seconds: 10
        max_attempts: 3
        retry_on: any
        command: npm test -- -- --reporter=json --reporter-option output=test-report.json
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: test-report.json
